//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type5/st25dvpwm/ST25DV02KW1Tag.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType5St25dvpwmST25DV02KW1Tag")
#ifdef RESTRICT_ComStSt25sdkType5St25dvpwmST25DV02KW1Tag
#define INCLUDE_ALL_ComStSt25sdkType5St25dvpwmST25DV02KW1Tag 0
#else
#define INCLUDE_ALL_ComStSt25sdkType5St25dvpwmST25DV02KW1Tag 1
#endif
#undef RESTRICT_ComStSt25sdkType5St25dvpwmST25DV02KW1Tag

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType5St25dvpwmST25DV02KW1Tag_) && (INCLUDE_ALL_ComStSt25sdkType5St25dvpwmST25DV02KW1Tag || defined(INCLUDE_ComStSt25sdkType5St25dvpwmST25DV02KW1Tag))
#define ComStSt25sdkType5St25dvpwmST25DV02KW1Tag_

#define RESTRICT_ComStSt25sdkType5St25dvpwmST25DVPwmTag 1
#define INCLUDE_ComStSt25sdkType5St25dvpwmST25DVPwmTag 1
#include "com/st/st25sdk/type5/st25dvpwm/ST25DVPwmTag.h"

@class IOSByteArray;
@protocol ComStSt25sdkRFReaderInterface;

@interface ComStSt25sdkType5St25dvpwmST25DV02KW1Tag : ComStSt25sdkType5St25dvpwmST25DVPwmTag

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                  withByteArray:(IOSByteArray *)uid;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType5St25dvpwmST25DV02KW1Tag)

FOUNDATION_EXPORT void ComStSt25sdkType5St25dvpwmST25DV02KW1Tag_initWithComStSt25sdkRFReaderInterface_withByteArray_(ComStSt25sdkType5St25dvpwmST25DV02KW1Tag *self, id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkType5St25dvpwmST25DV02KW1Tag *new_ComStSt25sdkType5St25dvpwmST25DV02KW1Tag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType5St25dvpwmST25DV02KW1Tag *create_ComStSt25sdkType5St25dvpwmST25DV02KW1Tag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType5St25dvpwmST25DV02KW1Tag)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType5St25dvpwmST25DV02KW1Tag")
