//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/command/Iso15693CustomKillCommandInterface.java
//

#include "J2ObjC_source.h"
#include "com/st/st25sdk/command/Iso15693CustomKillCommandInterface.h"

@interface ComStSt25sdkCommandIso15693CustomKillCommandInterface : NSObject

@end

@implementation ComStSt25sdkCommandIso15693CustomKillCommandInterface

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "B", 0x401, 0, 1, 2, -1, -1, -1 },
    { NULL, "B", 0x401, 3, 1, 2, -1, -1, -1 },
    { NULL, "B", 0x401, -1, -1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(killWithByteArray:);
  methods[1].selector = @selector(writeKillWithByteArray:);
  methods[2].selector = @selector(lockKill);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "kill", "[B", "LComStSt25sdkSTException;", "writeKill" };
  static const J2ObjcClassInfo _ComStSt25sdkCommandIso15693CustomKillCommandInterface = { "Iso15693CustomKillCommandInterface", "com.st.st25sdk.command", ptrTable, methods, NULL, 7, 0x609, 3, 0, -1, -1, -1, -1, -1 };
  return &_ComStSt25sdkCommandIso15693CustomKillCommandInterface;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComStSt25sdkCommandIso15693CustomKillCommandInterface)
