//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/command/Iso15693CustomCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkCommandIso15693CustomCommand")
#ifdef RESTRICT_ComStSt25sdkCommandIso15693CustomCommand
#define INCLUDE_ALL_ComStSt25sdkCommandIso15693CustomCommand 0
#else
#define INCLUDE_ALL_ComStSt25sdkCommandIso15693CustomCommand 1
#endif
#undef RESTRICT_ComStSt25sdkCommandIso15693CustomCommand

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkCommandIso15693CustomCommand_) && (INCLUDE_ALL_ComStSt25sdkCommandIso15693CustomCommand || defined(INCLUDE_ComStSt25sdkCommandIso15693CustomCommand))
#define ComStSt25sdkCommandIso15693CustomCommand_

#define RESTRICT_ComStSt25sdkCommandIso15693Command 1
#define INCLUDE_ComStSt25sdkCommandIso15693Command 1
#include "com/st/st25sdk/command/Iso15693Command.h"

#define RESTRICT_ComStSt25sdkCommandIso15693CustomCommandInterface 1
#define INCLUDE_ComStSt25sdkCommandIso15693CustomCommandInterface 1
#include "com/st/st25sdk/command/Iso15693CustomCommandInterface.h"

@class IOSByteArray;
@protocol ComStSt25sdkRFReaderInterface;

@interface ComStSt25sdkCommandIso15693CustomCommand : ComStSt25sdkCommandIso15693Command < ComStSt25sdkCommandIso15693CustomCommandInterface >
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_READ_CONFIG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_READ_CONFIG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_WRITE_CONFIG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_WRITE_CONFIG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_READ_DYN_CONFIG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_READ_DYN_CONFIG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_WRITE_DYN_CONFIG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_WRITE_DYN_CONFIG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_WRITE_PASSWORD NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_WRITE_PASSWORD);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_LOCK_SECTOR NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_LOCK_SECTOR);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_PRESENT_PASSWORD NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_PRESENT_PASSWORD);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_GET_RANDOM_NUMBER NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_GET_RANDOM_NUMBER);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_FAST_READ_SINGLE_BLOCK NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_FAST_READ_SINGLE_BLOCK);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_FAST_READ_MULTIPLE_BLOCK NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_FAST_READ_MULTIPLE_BLOCK);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_FAST_READ_DYN_CONFIG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_FAST_READ_DYN_CONFIG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_FAST_WRITE_DYN_CONFIG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_FAST_WRITE_DYN_CONFIG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_SINGLE_BLOCK NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_SINGLE_BLOCK);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_MULTIPLE_BLOCK NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_MULTIPLE_BLOCK);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_KILL NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_KILL);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_WRITE_KILL NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_WRITE_KILL);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_LOCK_KILL NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_LOCK_KILL);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_PARAM_KILL_ACCESS NS_SWIFT_NAME(ISO15693_CUSTOM_ST_PARAM_KILL_ACCESS);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_INVENTORY_INITIATED NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_INVENTORY_INITIATED);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_INITIATE NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_INITIATE);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_FAST_INITIATE NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_FAST_INITIATE);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_INITIATED NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_INITIATED);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_WRITE_EH_CFG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_WRITE_EH_CFG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_SET_RST_EH_EN NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_SET_RST_EH_EN);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_CHECK_EH_EN NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_CHECK_EH_EN);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_WRITE_DO_CFG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_WRITE_DO_CFG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_MANAGE_GPO NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_MANAGE_GPO);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_MB_WRITE_MSG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_MB_WRITE_MSG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_MB_READ_MSG_LENGTH NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_MB_READ_MSG_LENGTH);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_MB_READ_MSG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_MB_READ_MSG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_MB_FAST_WRITE_MSG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_MB_FAST_WRITE_MSG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG_LENGTH NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG_LENGTH);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_SET_EAS NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_SET_EAS);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_RESET_EAS NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_RESET_EAS);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_LOCK_EAS NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_LOCK_EAS);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_ENABLE_EAS NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_ENABLE_EAS);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_WRITE_EAS_ID NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_WRITE_EAS_ID);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_WRITE_EAS_CONFIG NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_WRITE_EAS_CONFIG);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_ENABLE_UNTRACEABLE_MODE NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_ENABLE_UNTRACEABLE_MODE);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_TOGGLE_UNTRACEABLE_MODE NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_TOGGLE_UNTRACEABLE_MODE);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_INVENTORY_READ NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_INVENTORY_READ);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_READ NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_READ);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_CMD_READ_SIGNATURE NS_SWIFT_NAME(ISO15693_CUSTOM_ST_CMD_READ_SIGNATURE);
@property (readonly, class) jbyte ISO15693_CUSTOM_ST_PARAM_UNTRACEABLE_ACCESS_CODE NS_SWIFT_NAME(ISO15693_CUSTOM_ST_PARAM_UNTRACEABLE_ACCESS_CODE);

+ (jbyte)ISO15693_CUSTOM_ST_CMD_READ_CONFIG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_WRITE_CONFIG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_READ_DYN_CONFIG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_WRITE_DYN_CONFIG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_WRITE_PASSWORD;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_LOCK_SECTOR;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_PRESENT_PASSWORD;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_GET_RANDOM_NUMBER;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_FAST_READ_SINGLE_BLOCK;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_FAST_READ_MULTIPLE_BLOCK;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_FAST_READ_DYN_CONFIG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_FAST_WRITE_DYN_CONFIG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_SINGLE_BLOCK;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_MULTIPLE_BLOCK;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_KILL;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_WRITE_KILL;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_LOCK_KILL;

+ (jbyte)ISO15693_CUSTOM_ST_PARAM_KILL_ACCESS;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_INVENTORY_INITIATED;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_INITIATE;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_FAST_INITIATE;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_INITIATED;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_WRITE_EH_CFG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_SET_RST_EH_EN;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_CHECK_EH_EN;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_WRITE_DO_CFG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_MANAGE_GPO;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_MB_WRITE_MSG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_MB_READ_MSG_LENGTH;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_MB_READ_MSG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_MB_FAST_WRITE_MSG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG_LENGTH;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_SET_EAS;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_RESET_EAS;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_LOCK_EAS;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_ENABLE_EAS;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_WRITE_EAS_ID;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_WRITE_EAS_CONFIG;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_ENABLE_UNTRACEABLE_MODE;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_TOGGLE_UNTRACEABLE_MODE;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_INVENTORY_READ;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_READ;

+ (jbyte)ISO15693_CUSTOM_ST_CMD_READ_SIGNATURE;

+ (jbyte)ISO15693_CUSTOM_ST_PARAM_UNTRACEABLE_ACCESS_CODE;

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)reader
                                                  withByteArray:(IOSByteArray *)uid;

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)reader
                                                  withByteArray:(IOSByteArray *)uid
                                                       withByte:(jbyte)flag;

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)reader
                                                  withByteArray:(IOSByteArray *)uid
                                                       withByte:(jbyte)flag
                                                        withInt:(jint)nbrOfBytesPerBlock;

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)reader
                                                  withByteArray:(IOSByteArray *)uid
                                                        withInt:(jint)nbrOfBytesPerBlock;

- (IOSByteArray *)checkEHEnWithByte:(jbyte)flag
                      withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)enableEAS;

- (IOSByteArray *)enableEASWithByte:(jbyte)flag
                      withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)enableEASWithByte:(jbyte)easIdMask
                      withByteArray:(IOSByteArray *)easId
                           withByte:(jbyte)flag
                      withByteArray:(IOSByteArray *)uid;

- (jbyte)enableUntraceableModeWithByteArray:(IOSByteArray *)obfuscatedUntraceableModePassword;

- (jbyte)enableUntraceableModeWithByteArray:(IOSByteArray *)obfuscatedUntraceableModePassword
                                   withByte:(jbyte)flag
                              withByteArray:(IOSByteArray *)uid;

- (jbyte)enableUntraceableModeWithByteArray:(IOSByteArray *)obfuscatedUntraceableModePassword
                                    withInt:(jint)untraceablePasswordNumber
                                   withByte:(jbyte)flag
                              withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)fastExtendedReadMultipleBlockWithByteArray:(IOSByteArray *)blockAddress
                                               withByteArray:(IOSByteArray *)nbrOfBlocks;

- (IOSByteArray *)fastExtendedReadMultipleBlockWithByteArray:(IOSByteArray *)blockAddress
                                               withByteArray:(IOSByteArray *)nbrOfBlocks
                                                    withByte:(jbyte)flag
                                               withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)fastExtendedReadSingleBlockWithByteArray:(IOSByteArray *)blockAddress;

- (IOSByteArray *)fastExtendedReadSingleBlockWithByteArray:(IOSByteArray *)blockAddress
                                                  withByte:(jbyte)flag
                                             withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)fastInitiateWithByte:(jbyte)flag;

- (IOSByteArray *)fastInventoryInitiatedWithByte:(jbyte)flag;

- (IOSByteArray *)fastInventoryInitiatedWithByte:(jbyte)flag
                                        withByte:(jbyte)afiField;

- (IOSByteArray *)fastInventoryInitiatedWithByte:(jbyte)flag
                                        withByte:(jbyte)maskLengthInBits
                                   withByteArray:(IOSByteArray *)maskValue;

- (IOSByteArray *)fastInventoryInitiatedWithByte:(jbyte)flag
                                        withByte:(jbyte)maskLengthInBits
                                   withByteArray:(IOSByteArray *)maskValue
                                        withByte:(jbyte)afiField;

- (IOSByteArray *)fastInventoryReadWithByte:(jbyte)flag
                                   withByte:(jbyte)blockAddress
                                   withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)fastInventoryReadWithByte:(jbyte)flag
                                   withByte:(jbyte)afiField
                                   withByte:(jbyte)blockAddress
                                   withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)fastInventoryReadWithByte:(jbyte)flag
                                   withByte:(jbyte)maskLengthInBits
                              withByteArray:(IOSByteArray *)maskValue
                                   withByte:(jbyte)blockAddress
                                   withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)fastInventoryReadWithByte:(jbyte)flag
                                   withByte:(jbyte)maskLengthInBits
                              withByteArray:(IOSByteArray *)maskValue
                                   withByte:(jbyte)afiField
                                   withByte:(jbyte)blockAddress
                                   withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)fastReadDynConfigWithByte:(jbyte)configId;

- (IOSByteArray *)fastReadDynConfigWithByte:(jbyte)configId
                                   withByte:(jbyte)flag
                              withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)fastReadMsgWithByte:(jbyte)offset
                             withByte:(jbyte)sizeInBytes;

- (IOSByteArray *)fastReadMsgWithByte:(jbyte)offset
                             withByte:(jbyte)sizeInBytes
                             withByte:(jbyte)flag
                        withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)fastReadMsgLength;

- (IOSByteArray *)fastReadMsgLengthWithByte:(jbyte)flag
                              withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)fastReadMultipleBlockWithByte:(jbyte)blockAddress
                                       withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)fastReadMultipleBlockWithByte:(jbyte)blockAddress
                                       withByte:(jbyte)nbrOfBlocks
                                       withByte:(jbyte)flag
                                  withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)fastReadSingleBlockWithByte:(jbyte)blockAddress;

- (IOSByteArray *)fastReadSingleBlockWithByte:(jbyte)blockAddress
                                     withByte:(jbyte)flag
                                withByteArray:(IOSByteArray *)uid;

- (jbyte)fastWriteDynConfigWithByte:(jbyte)configId
                           withByte:(jbyte)newAttributeValue;

- (jbyte)fastWriteDynConfigWithByte:(jbyte)configId
                           withByte:(jbyte)newAttributeValue
                           withByte:(jbyte)flag
                      withByteArray:(IOSByteArray *)uid;

- (jbyte)fastWriteMsgWithByte:(jbyte)sizeInBytes
                withByteArray:(IOSByteArray *)buffer;

- (jbyte)fastWriteMsgWithByte:(jbyte)sizeInBytes
                withByteArray:(IOSByteArray *)buffer
                     withByte:(jbyte)flag
                withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)getRandomNumber;

- (IOSByteArray *)getRandomNumberWithByte:(jbyte)flag;

- (IOSByteArray *)getRandomNumberWithByte:(jbyte)flag
                            withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)initiateWithByte:(jbyte)flag OBJC_METHOD_FAMILY_NONE;

- (IOSByteArray *)inventoryInitiatedWithByte:(jbyte)flag;

- (IOSByteArray *)inventoryInitiatedWithByte:(jbyte)flag
                                    withByte:(jbyte)afiField;

- (IOSByteArray *)inventoryInitiatedWithByte:(jbyte)flag
                                    withByte:(jbyte)maskLengthInBits
                               withByteArray:(IOSByteArray *)maskValue;

- (IOSByteArray *)inventoryInitiatedWithByte:(jbyte)flag
                                    withByte:(jbyte)maskLengthInBits
                               withByteArray:(IOSByteArray *)maskValue
                                    withByte:(jbyte)afiField;

- (IOSByteArray *)inventoryReadWithByte:(jbyte)flag
                               withByte:(jbyte)blockAddress
                               withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)inventoryReadWithByte:(jbyte)flag
                               withByte:(jbyte)afiField
                               withByte:(jbyte)blockAddress
                               withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)inventoryReadWithByte:(jbyte)flag
                               withByte:(jbyte)maskLengthInBits
                          withByteArray:(IOSByteArray *)maskValue
                               withByte:(jbyte)blockAddress
                               withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)inventoryReadWithByte:(jbyte)flag
                               withByte:(jbyte)maskLengthInBits
                          withByteArray:(IOSByteArray *)maskValue
                               withByte:(jbyte)afiField
                               withByte:(jbyte)blockAddress
                               withByte:(jbyte)nbrOfBlocks;

- (jbyte)killWithByteArray:(IOSByteArray *)unencryptedKillCode;

- (jbyte)killWithByteArray:(IOSByteArray *)unencryptedKillCode
                  withByte:(jbyte)flag
             withByteArray:(IOSByteArray *)uid;

- (jbyte)lockEas;

- (jbyte)lockEasWithByte:(jbyte)flag
           withByteArray:(IOSByteArray *)uid;

- (jbyte)lockKill;

- (jbyte)lockKillWithByte:(jbyte)flag
            withByteArray:(IOSByteArray *)uid;

- (jbyte)lockSectorWithByte:(jbyte)blockAddress
                   withByte:(jbyte)securityStatus;

- (jbyte)lockSectorWithByte:(jbyte)blockAddress
                   withByte:(jbyte)securityStatus
                   withByte:(jbyte)flag
              withByteArray:(IOSByteArray *)uid;

- (jbyte)manageGpoWithByte:(jbyte)value
                  withByte:(jbyte)flag
             withByteArray:(IOSByteArray *)uid;

- (jbyte)presentPwdWithByte:(jbyte)passwordNumber
              withByteArray:(IOSByteArray *)password;

- (jbyte)presentPwdWithByte:(jbyte)passwordNumber
              withByteArray:(IOSByteArray *)password
                   withByte:(jbyte)flag
              withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)readCfg;

- (IOSByteArray *)readCfgWithByte:(jbyte)flag
                    withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)readConfigWithByte:(jbyte)configId;

- (IOSByteArray *)readConfigWithByte:(jbyte)fid
                            withByte:(jbyte)pid;

- (IOSByteArray *)readConfigWithByte:(jbyte)fid
                            withByte:(jbyte)pid
                            withByte:(jbyte)flag
                       withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)readConfigWithByte:(jbyte)configId
                            withByte:(jbyte)flag
                       withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)readDynConfigWithByte:(jbyte)configId;

- (IOSByteArray *)readDynConfigWithByte:(jbyte)configId
                               withByte:(jbyte)flag
                          withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)readMsgWithByte:(jbyte)offset
                         withByte:(jbyte)sizeInBytes;

- (IOSByteArray *)readMsgWithByte:(jbyte)offset
                         withByte:(jbyte)sizeInBytes
                         withByte:(jbyte)flag
                    withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)readMsgLength;

- (IOSByteArray *)readMsgLengthWithByte:(jbyte)flag
                          withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)readSignature;

- (IOSByteArray *)readSignatureWithByte:(jbyte)flag
                          withByteArray:(IOSByteArray *)uid;

- (jbyte)resetEas;

- (jbyte)resetEasWithByte:(jbyte)flag
            withByteArray:(IOSByteArray *)uid;

- (jbyte)setEas;

- (jbyte)setEasWithByte:(jbyte)flag
          withByteArray:(IOSByteArray *)uid;

- (jbyte)setRstEHEnWithByte:(jbyte)data
                   withByte:(jbyte)flag
              withByteArray:(IOSByteArray *)uid;

- (jbyte)toggleUntraceableModeWithByteArray:(IOSByteArray *)obfuscatedUntraceableModePassword
                                    withInt:(jint)untraceablePasswordNumber;

- (jbyte)toggleUntraceableModeWithByteArray:(IOSByteArray *)obfuscatedUntraceableModePassword
                                    withInt:(jint)untraceablePasswordNumber
                                   withByte:(jbyte)flag
                              withByteArray:(IOSByteArray *)uid;

- (jbyte)writeConfigWithByte:(jbyte)configId
                    withByte:(jbyte)newAttributeValue;

- (jbyte)writeConfigWithByte:(jbyte)registerFeatureId
                    withByte:(jbyte)registerParameterId
                    withByte:(jbyte)newAttributeValue;

- (jbyte)writeConfigWithByte:(jbyte)registerFeatureId
                    withByte:(jbyte)registerParameterId
                    withByte:(jbyte)newAttributeValue
                    withByte:(jbyte)flag
               withByteArray:(IOSByteArray *)uid;

- (jbyte)writeConfigWithByte:(jbyte)configId
                    withByte:(jbyte)newAttributeValue
                    withByte:(jbyte)flag
               withByteArray:(IOSByteArray *)uid;

- (jbyte)writeConfigWithByte:(jbyte)registerFeatureId
                    withByte:(jbyte)registerParameterId
               withByteArray:(IOSByteArray *)newRegisterValue;

- (jbyte)writeConfigWithByte:(jbyte)registerFeatureId
                    withByte:(jbyte)registerParameterId
               withByteArray:(IOSByteArray *)newRegisterValue
                    withByte:(jbyte)flag
               withByteArray:(IOSByteArray *)uid;

- (jbyte)writeConfigWithByte:(jbyte)configId
               withByteArray:(IOSByteArray *)newRegisterValue;

- (jbyte)writeConfigWithByte:(jbyte)configId
               withByteArray:(IOSByteArray *)newRegisterValue
                    withByte:(jbyte)flag
               withByteArray:(IOSByteArray *)uid;

- (jbyte)writeDOCfgWithByte:(jbyte)data
                   withByte:(jbyte)flag
              withByteArray:(IOSByteArray *)uid;

- (jbyte)writeDynConfigWithByte:(jbyte)configId
                       withByte:(jbyte)newAttributeValue;

- (jbyte)writeDynConfigWithByte:(jbyte)configId
                       withByte:(jbyte)newAttributeValue
                       withByte:(jbyte)flag
                  withByteArray:(IOSByteArray *)uid;

- (jbyte)writeEasConfigWithByte:(jbyte)config;

- (jbyte)writeEasConfigWithByte:(jbyte)config
                       withByte:(jbyte)flag
                  withByteArray:(IOSByteArray *)uid;

- (jbyte)writeEasIdWithByteArray:(IOSByteArray *)easId;

- (jbyte)writeEasIdWithByteArray:(IOSByteArray *)easId
                        withByte:(jbyte)flag
                   withByteArray:(IOSByteArray *)uid;

- (jbyte)writeEHCfgWithByte:(jbyte)data
                   withByte:(jbyte)flag
              withByteArray:(IOSByteArray *)uid;

- (jbyte)writeKillWithByteArray:(IOSByteArray *)unencryptedKillPassword;

- (jbyte)writeKillWithByteArray:(IOSByteArray *)unencryptedKillPassword
                       withByte:(jbyte)flag
                  withByteArray:(IOSByteArray *)uid;

- (jbyte)writeMsgWithByte:(jbyte)sizeInBytes
            withByteArray:(IOSByteArray *)buffer;

- (jbyte)writeMsgWithByte:(jbyte)sizeInBytes
            withByteArray:(IOSByteArray *)buffer
                 withByte:(jbyte)flag
            withByteArray:(IOSByteArray *)uid;

- (jbyte)writePwdWithByte:(jbyte)passwordNumber
            withByteArray:(IOSByteArray *)newPassword;

- (jbyte)writePwdWithByte:(jbyte)passwordNumber
            withByteArray:(IOSByteArray *)newPassword
                 withByte:(jbyte)flag
            withByteArray:(IOSByteArray *)uid;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkCommandIso15693CustomCommand)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_READ_CONFIG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_READ_CONFIG -96
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_READ_CONFIG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_WRITE_CONFIG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_WRITE_CONFIG -95
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_WRITE_CONFIG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_READ_DYN_CONFIG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_READ_DYN_CONFIG -83
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_READ_DYN_CONFIG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_WRITE_DYN_CONFIG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_WRITE_DYN_CONFIG -82
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_WRITE_DYN_CONFIG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_WRITE_PASSWORD(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_WRITE_PASSWORD -79
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_WRITE_PASSWORD, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_LOCK_SECTOR(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_LOCK_SECTOR -78
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_LOCK_SECTOR, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_PRESENT_PASSWORD(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_PRESENT_PASSWORD -77
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_PRESENT_PASSWORD, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_GET_RANDOM_NUMBER(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_GET_RANDOM_NUMBER -76
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_GET_RANDOM_NUMBER, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_FAST_READ_SINGLE_BLOCK(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_FAST_READ_SINGLE_BLOCK -64
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_FAST_READ_SINGLE_BLOCK, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_FAST_READ_MULTIPLE_BLOCK(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_FAST_READ_MULTIPLE_BLOCK -61
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_FAST_READ_MULTIPLE_BLOCK, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_FAST_READ_DYN_CONFIG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_FAST_READ_DYN_CONFIG -51
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_FAST_READ_DYN_CONFIG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_FAST_WRITE_DYN_CONFIG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_FAST_WRITE_DYN_CONFIG -50
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_FAST_WRITE_DYN_CONFIG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_SINGLE_BLOCK(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_SINGLE_BLOCK -60
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_SINGLE_BLOCK, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_MULTIPLE_BLOCK(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_MULTIPLE_BLOCK -59
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_FAST_EXTENDED_READ_MULTIPLE_BLOCK, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_KILL(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_KILL -90
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_KILL, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_WRITE_KILL(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_WRITE_KILL -79
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_WRITE_KILL, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_LOCK_KILL(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_LOCK_KILL -78
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_LOCK_KILL, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_PARAM_KILL_ACCESS(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_PARAM_KILL_ACCESS 0
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_PARAM_KILL_ACCESS, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_INVENTORY_INITIATED(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_INVENTORY_INITIATED -47
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_INVENTORY_INITIATED, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_INITIATE(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_INITIATE -46
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_INITIATE, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_FAST_INITIATE(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_FAST_INITIATE -62
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_FAST_INITIATE, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_INITIATED(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_INITIATED -63
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_INITIATED, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_WRITE_EH_CFG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_WRITE_EH_CFG -95
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_WRITE_EH_CFG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_SET_RST_EH_EN(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_SET_RST_EH_EN -94
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_SET_RST_EH_EN, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_CHECK_EH_EN(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_CHECK_EH_EN -93
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_CHECK_EH_EN, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_WRITE_DO_CFG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_WRITE_DO_CFG -92
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_WRITE_DO_CFG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_MANAGE_GPO(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_MANAGE_GPO -87
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_MANAGE_GPO, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_MB_WRITE_MSG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_MB_WRITE_MSG -86
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_MB_WRITE_MSG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_MB_READ_MSG_LENGTH(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_MB_READ_MSG_LENGTH -85
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_MB_READ_MSG_LENGTH, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_MB_READ_MSG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_MB_READ_MSG -84
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_MB_READ_MSG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_MB_FAST_WRITE_MSG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_MB_FAST_WRITE_MSG -54
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_MB_FAST_WRITE_MSG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG_LENGTH(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG_LENGTH -53
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG_LENGTH, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG -52
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_MB_FAST_READ_MSG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_SET_EAS(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_SET_EAS -94
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_SET_EAS, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_RESET_EAS(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_RESET_EAS -93
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_RESET_EAS, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_LOCK_EAS(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_LOCK_EAS -92
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_LOCK_EAS, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_ENABLE_EAS(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_ENABLE_EAS -91
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_ENABLE_EAS, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_WRITE_EAS_ID(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_WRITE_EAS_ID -89
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_WRITE_EAS_ID, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_WRITE_EAS_CONFIG(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_WRITE_EAS_CONFIG -88
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_WRITE_EAS_CONFIG, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_ENABLE_UNTRACEABLE_MODE(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_ENABLE_UNTRACEABLE_MODE -70
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_ENABLE_UNTRACEABLE_MODE, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_TOGGLE_UNTRACEABLE_MODE(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_TOGGLE_UNTRACEABLE_MODE -70
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_TOGGLE_UNTRACEABLE_MODE, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_INVENTORY_READ(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_INVENTORY_READ -45
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_INVENTORY_READ, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_READ(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_READ -44
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_FAST_INVENTORY_READ, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_CMD_READ_SIGNATURE(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_CMD_READ_SIGNATURE -37
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_CMD_READ_SIGNATURE, jbyte)

inline jbyte ComStSt25sdkCommandIso15693CustomCommand_get_ISO15693_CUSTOM_ST_PARAM_UNTRACEABLE_ACCESS_CODE(void);
#define ComStSt25sdkCommandIso15693CustomCommand_ISO15693_CUSTOM_ST_PARAM_UNTRACEABLE_ACCESS_CODE 0
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkCommandIso15693CustomCommand, ISO15693_CUSTOM_ST_PARAM_UNTRACEABLE_ACCESS_CODE, jbyte)

FOUNDATION_EXPORT void ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_(ComStSt25sdkCommandIso15693CustomCommand *self, id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkCommandIso15693CustomCommand *new_ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkCommandIso15693CustomCommand *create_ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid);

FOUNDATION_EXPORT void ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_(ComStSt25sdkCommandIso15693CustomCommand *self, id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag);

FOUNDATION_EXPORT ComStSt25sdkCommandIso15693CustomCommand *new_ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkCommandIso15693CustomCommand *create_ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag);

FOUNDATION_EXPORT void ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withInt_(ComStSt25sdkCommandIso15693CustomCommand *self, id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jint nbrOfBytesPerBlock);

FOUNDATION_EXPORT ComStSt25sdkCommandIso15693CustomCommand *new_ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withInt_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jint nbrOfBytesPerBlock) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkCommandIso15693CustomCommand *create_ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withInt_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jint nbrOfBytesPerBlock);

FOUNDATION_EXPORT void ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_withInt_(ComStSt25sdkCommandIso15693CustomCommand *self, id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag, jint nbrOfBytesPerBlock);

FOUNDATION_EXPORT ComStSt25sdkCommandIso15693CustomCommand *new_ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_withInt_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag, jint nbrOfBytesPerBlock) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkCommandIso15693CustomCommand *create_ComStSt25sdkCommandIso15693CustomCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_withInt_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag, jint nbrOfBytesPerBlock);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkCommandIso15693CustomCommand)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkCommandIso15693CustomCommand")
