//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/command/VicinityCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkCommandVicinityCommand")
#ifdef RESTRICT_ComStSt25sdkCommandVicinityCommand
#define INCLUDE_ALL_ComStSt25sdkCommandVicinityCommand 0
#else
#define INCLUDE_ALL_ComStSt25sdkCommandVicinityCommand 1
#endif
#undef RESTRICT_ComStSt25sdkCommandVicinityCommand

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkCommandVicinityCommand_) && (INCLUDE_ALL_ComStSt25sdkCommandVicinityCommand || defined(INCLUDE_ComStSt25sdkCommandVicinityCommand))
#define ComStSt25sdkCommandVicinityCommand_

#define RESTRICT_ComStSt25sdkCommandIso15693Protocol 1
#define INCLUDE_ComStSt25sdkCommandIso15693Protocol 1
#include "com/st/st25sdk/command/Iso15693Protocol.h"

#define RESTRICT_ComStSt25sdkCommandVicinityCommandInterface 1
#define INCLUDE_ComStSt25sdkCommandVicinityCommandInterface 1
#include "com/st/st25sdk/command/VicinityCommandInterface.h"

@class IOSByteArray;
@protocol ComStSt25sdkRFReaderInterface;

@interface ComStSt25sdkCommandVicinityCommand : ComStSt25sdkCommandIso15693Protocol < ComStSt25sdkCommandVicinityCommandInterface >

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)reader
                                                  withByteArray:(IOSByteArray *)uid;

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)reader
                                                  withByteArray:(IOSByteArray *)uid
                                                       withByte:(jbyte)flag;

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)reader
                                                  withByteArray:(IOSByteArray *)uid
                                                       withByte:(jbyte)flag
                                                        withInt:(jint)nbrOfBytesPerBlock;

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)reader
                                                  withByteArray:(IOSByteArray *)uid
                                                        withInt:(jint)nbrOfBytesPerBlock;

- (IOSByteArray *)fastReadMultipleBlockWithByte:(jbyte)blockOffset
                                       withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)fastReadMultipleBlockWithByteArray:(IOSByteArray *)blockAddress
                                            withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)fastReadMultipleBlockWithByteArray:(IOSByteArray *)blockAddress
                                            withByte:(jbyte)nbrOfBlocks
                                            withByte:(jbyte)flag
                                       withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)fastReadSingleBlockWithByte:(jbyte)blockOffset;

- (IOSByteArray *)fastReadSingleBlockWithByteArray:(IOSByteArray *)blockAddress;

- (IOSByteArray *)fastReadSingleBlockWithByteArray:(IOSByteArray *)blockAddress
                                          withByte:(jbyte)flag
                                     withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)getMultipleBlockSecStatusWithByteArray:(IOSByteArray *)firstBlock
                                           withByteArray:(IOSByteArray *)nbOfBlocks;

- (IOSByteArray *)getMultipleBlockSecStatusWithByteArray:(IOSByteArray *)firstBlock
                                           withByteArray:(IOSByteArray *)nbrOfBlocks
                                                withByte:(jbyte)flag
                                           withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)getSystemInfo;

- (IOSByteArray *)getSystemInfoWithByte:(jbyte)flag
                          withByteArray:(IOSByteArray *)uid;

- (jbyte)lockSectorWithByteArray:(IOSByteArray *)blockAddress
                        withByte:(jbyte)securityStatus;

- (jbyte)lockSectorWithByteArray:(IOSByteArray *)blockAddress
                        withByte:(jbyte)securityStatus
                        withByte:(jbyte)flag
                   withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)readMultipleBlockWithByteArray:(IOSByteArray *)blockAddress
                                        withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)readMultipleBlockWithByteArray:(IOSByteArray *)blockAddress
                                        withByte:(jbyte)nbrOfBlocks
                                        withByte:(jbyte)flag
                                   withByteArray:(IOSByteArray *)uid;

- (IOSByteArray *)readSingleBlockWithByteArray:(IOSByteArray *)blockAddress;

- (IOSByteArray *)readSingleBlockWithByteArray:(IOSByteArray *)blockAddress
                                      withByte:(jbyte)flag
                                 withByteArray:(IOSByteArray *)uid;

- (jbyte)writeSingleBlockWithByteArray:(IOSByteArray *)blockAddress
                         withByteArray:(IOSByteArray *)buffer;

- (jbyte)writeSingleBlockWithByteArray:(IOSByteArray *)blockAddress
                         withByteArray:(IOSByteArray *)buffer
                              withByte:(jbyte)flag
                         withByteArray:(IOSByteArray *)uid;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkCommandVicinityCommand)

FOUNDATION_EXPORT void ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_(ComStSt25sdkCommandVicinityCommand *self, id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkCommandVicinityCommand *new_ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkCommandVicinityCommand *create_ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid);

FOUNDATION_EXPORT void ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_(ComStSt25sdkCommandVicinityCommand *self, id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag);

FOUNDATION_EXPORT ComStSt25sdkCommandVicinityCommand *new_ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkCommandVicinityCommand *create_ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag);

FOUNDATION_EXPORT void ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withInt_(ComStSt25sdkCommandVicinityCommand *self, id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jint nbrOfBytesPerBlock);

FOUNDATION_EXPORT ComStSt25sdkCommandVicinityCommand *new_ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withInt_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jint nbrOfBytesPerBlock) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkCommandVicinityCommand *create_ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withInt_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jint nbrOfBytesPerBlock);

FOUNDATION_EXPORT void ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_withInt_(ComStSt25sdkCommandVicinityCommand *self, id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag, jint nbrOfBytesPerBlock);

FOUNDATION_EXPORT ComStSt25sdkCommandVicinityCommand *new_ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_withInt_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag, jint nbrOfBytesPerBlock) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkCommandVicinityCommand *create_ComStSt25sdkCommandVicinityCommand_initWithComStSt25sdkRFReaderInterface_withByteArray_withByte_withInt_(id<ComStSt25sdkRFReaderInterface> reader, IOSByteArray *uid, jbyte flag, jint nbrOfBytesPerBlock);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkCommandVicinityCommand)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkCommandVicinityCommand")
