//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/ndef/TnepServiceSelectRecord.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkNdefTnepServiceSelectRecord")
#ifdef RESTRICT_ComStSt25sdkNdefTnepServiceSelectRecord
#define INCLUDE_ALL_ComStSt25sdkNdefTnepServiceSelectRecord 0
#else
#define INCLUDE_ALL_ComStSt25sdkNdefTnepServiceSelectRecord 1
#endif
#undef RESTRICT_ComStSt25sdkNdefTnepServiceSelectRecord

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkNdefTnepServiceSelectRecord_) && (INCLUDE_ALL_ComStSt25sdkNdefTnepServiceSelectRecord || defined(INCLUDE_ComStSt25sdkNdefTnepServiceSelectRecord))
#define ComStSt25sdkNdefTnepServiceSelectRecord_

#define RESTRICT_ComStSt25sdkNdefNDEFRecord 1
#define INCLUDE_ComStSt25sdkNdefNDEFRecord 1
#include "com/st/st25sdk/ndef/NDEFRecord.h"

@class IOSByteArray;
@class JavaIoByteArrayInputStream;

@interface ComStSt25sdkNdefTnepServiceSelectRecord : ComStSt25sdkNdefNDEFRecord

#pragma mark Public

- (instancetype __nonnull)initWithJavaIoByteArrayInputStream:(JavaIoByteArrayInputStream *)inputStream;

- (instancetype __nonnull)initWithNSString:(NSString *)serviceName;

- (IOSByteArray *)getPayload;

- (NSString *)getServiceName;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

- (instancetype __nonnull)initWithByteArray:(IOSByteArray *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithComStSt25sdkNdefNDEFRecord:(ComStSt25sdkNdefNDEFRecord *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(ComStSt25sdkNdefTnepServiceSelectRecord)

FOUNDATION_EXPORT void ComStSt25sdkNdefTnepServiceSelectRecord_initWithNSString_(ComStSt25sdkNdefTnepServiceSelectRecord *self, NSString *serviceName);

FOUNDATION_EXPORT ComStSt25sdkNdefTnepServiceSelectRecord *new_ComStSt25sdkNdefTnepServiceSelectRecord_initWithNSString_(NSString *serviceName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkNdefTnepServiceSelectRecord *create_ComStSt25sdkNdefTnepServiceSelectRecord_initWithNSString_(NSString *serviceName);

FOUNDATION_EXPORT void ComStSt25sdkNdefTnepServiceSelectRecord_initWithJavaIoByteArrayInputStream_(ComStSt25sdkNdefTnepServiceSelectRecord *self, JavaIoByteArrayInputStream *inputStream);

FOUNDATION_EXPORT ComStSt25sdkNdefTnepServiceSelectRecord *new_ComStSt25sdkNdefTnepServiceSelectRecord_initWithJavaIoByteArrayInputStream_(JavaIoByteArrayInputStream *inputStream) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkNdefTnepServiceSelectRecord *create_ComStSt25sdkNdefTnepServiceSelectRecord_initWithJavaIoByteArrayInputStream_(JavaIoByteArrayInputStream *inputStream);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkNdefTnepServiceSelectRecord)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkNdefTnepServiceSelectRecord")
