//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type5/st25tv/ST25TVTag.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType5St25tvST25TVTag")
#ifdef RESTRICT_ComStSt25sdkType5St25tvST25TVTag
#define INCLUDE_ALL_ComStSt25sdkType5St25tvST25TVTag 0
#else
#define INCLUDE_ALL_ComStSt25sdkType5St25tvST25TVTag 1
#endif
#undef RESTRICT_ComStSt25sdkType5St25tvST25TVTag

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType5St25tvST25TVTag_) && (INCLUDE_ALL_ComStSt25sdkType5St25tvST25TVTag || defined(INCLUDE_ComStSt25sdkType5St25tvST25TVTag))
#define ComStSt25sdkType5St25tvST25TVTag_

#define RESTRICT_ComStSt25sdkType5STType5MultiAreaTag 1
#define INCLUDE_ComStSt25sdkType5STType5MultiAreaTag 1
#include "com/st/st25sdk/type5/STType5MultiAreaTag.h"

#define RESTRICT_ComStSt25sdkMultiAreaInterface 1
#define INCLUDE_ComStSt25sdkMultiAreaInterface 1
#include "com/st/st25sdk/MultiAreaInterface.h"

#define RESTRICT_ComStSt25sdkType5STType5PasswordInterface 1
#define INCLUDE_ComStSt25sdkType5STType5PasswordInterface 1
#include "com/st/st25sdk/type5/STType5PasswordInterface.h"

#define RESTRICT_ComStSt25sdkCommandIso15693CustomKillCommandInterface 1
#define INCLUDE_ComStSt25sdkCommandIso15693CustomKillCommandInterface 1
#include "com/st/st25sdk/command/Iso15693CustomKillCommandInterface.h"

#define RESTRICT_ComStSt25sdkUntraceableModeInterface 1
#define INCLUDE_ComStSt25sdkUntraceableModeInterface 1
#include "com/st/st25sdk/UntraceableModeInterface.h"

#define RESTRICT_ComStSt25sdkSignatureInterface 1
#define INCLUDE_ComStSt25sdkSignatureInterface 1
#include "com/st/st25sdk/SignatureInterface.h"

#define RESTRICT_ComStSt25sdkRegisterInterface 1
#define INCLUDE_ComStSt25sdkRegisterInterface 1
#include "com/st/st25sdk/RegisterInterface.h"

@class ComStSt25sdkSTRegister;
@class ComStSt25sdkTagHelper_ReadWriteProtection;
@class ComStSt25sdkType5St25tvST25TVRegisterCounterConfiguration;
@class ComStSt25sdkType5St25tvST25TVRegisterCounterValue;
@class ComStSt25sdkType5St25tvST25TVRegisterEasSecurityActivation;
@class ComStSt25sdkType5St25tvST25TVRegisterTamperConfiguration;
@class ComStSt25sdkUntraceableModeInterface_UntraceableModeDefaultSettings;
@class ComStSt25sdkUntraceableModeInterface_UntraceableModePolicy;
@class IOSByteArray;
@protocol ComStSt25sdkRFReaderInterface;
@protocol JavaUtilList;

@interface ComStSt25sdkType5St25tvST25TVTag : ComStSt25sdkType5STType5MultiAreaTag < ComStSt25sdkMultiAreaInterface, ComStSt25sdkType5STType5PasswordInterface, ComStSt25sdkCommandIso15693CustomKillCommandInterface, ComStSt25sdkUntraceableModeInterface, ComStSt25sdkSignatureInterface, ComStSt25sdkRegisterInterface >
@property (readonly, class) jint ST25TV_REGISTER_AREA1_SECURITY_ATTRIBUTE NS_SWIFT_NAME(ST25TV_REGISTER_AREA1_SECURITY_ATTRIBUTE);
@property (readonly, class) jint ST25TV_REGISTER_AREA2_SECURITY_ATTRIBUTE NS_SWIFT_NAME(ST25TV_REGISTER_AREA2_SECURITY_ATTRIBUTE);
@property (readonly, class) jint ST25TV_REGISTER_EAS_SECURITY_ACTIVATION NS_SWIFT_NAME(ST25TV_REGISTER_EAS_SECURITY_ACTIVATION);
@property (readonly, class) jint ST25TV_REGISTER_WRITE_COUNTER_CONFIGURATION NS_SWIFT_NAME(ST25TV_REGISTER_WRITE_COUNTER_CONFIGURATION);
@property (readonly, class) jint ST25TV_REGISTER_COUNTER_READ NS_SWIFT_NAME(ST25TV_REGISTER_COUNTER_READ);
@property (readonly, class) jint ST25TV_REGISTER_COUNTER_READ_LENGTH NS_SWIFT_NAME(ST25TV_REGISTER_COUNTER_READ_LENGTH);
@property (readonly, class) jint ST25TV_REGISTER_TAMPER_CONFIGURATION NS_SWIFT_NAME(ST25TV_REGISTER_TAMPER_CONFIGURATION);
@property (readonly, class) jint ST25TV_REGISTER_LOCK_CONFIGURATION NS_SWIFT_NAME(ST25TV_REGISTER_LOCK_CONFIGURATION);
@property (readonly, class) jint ST25TV_REGISTER_KEY_ID NS_SWIFT_NAME(ST25TV_REGISTER_KEY_ID);
@property (readonly, class) jint ST25TV_NUMBER_OF_REGISTERS NS_SWIFT_NAME(ST25TV_NUMBER_OF_REGISTERS);
@property (readonly, class) jint ST25TV_KILL_PASSWORD_ID NS_SWIFT_NAME(ST25TV_KILL_PASSWORD_ID);
@property (readonly, class) jint ST25TV_UNTRACEABLE_MODE_PASSWORD_ID NS_SWIFT_NAME(ST25TV_UNTRACEABLE_MODE_PASSWORD_ID);
@property (readonly, class) jint ST25TV_AREA1_PASSWORD_ID NS_SWIFT_NAME(ST25TV_AREA1_PASSWORD_ID);
@property (readonly, class) jint ST25TV_AREA2_PASSWORD_ID NS_SWIFT_NAME(ST25TV_AREA2_PASSWORD_ID);
@property (readonly, class) jint ST25TV_CONFIGURATION_PASSWORD_ID NS_SWIFT_NAME(ST25TV_CONFIGURATION_PASSWORD_ID);
@property (readonly, class) jint ST25TV_NUMBER_OF_PASSWORDS NS_SWIFT_NAME(ST25TV_NUMBER_OF_PASSWORDS);
@property (readonly, class) jint EAS_TELEGRAM_BLOCK_OFFSET NS_SWIFT_NAME(EAS_TELEGRAM_BLOCK_OFFSET);
@property (readonly, class) jint EAS_TELEGRAM_MAX_LENGTH NS_SWIFT_NAME(EAS_TELEGRAM_MAX_LENGTH);

+ (jint)ST25TV_REGISTER_AREA1_SECURITY_ATTRIBUTE;

+ (jint)ST25TV_REGISTER_AREA2_SECURITY_ATTRIBUTE;

+ (jint)ST25TV_REGISTER_EAS_SECURITY_ACTIVATION;

+ (jint)ST25TV_REGISTER_WRITE_COUNTER_CONFIGURATION;

+ (jint)ST25TV_REGISTER_COUNTER_READ;

+ (jint)ST25TV_REGISTER_COUNTER_READ_LENGTH;

+ (jint)ST25TV_REGISTER_TAMPER_CONFIGURATION;

+ (jint)ST25TV_REGISTER_LOCK_CONFIGURATION;

+ (jint)ST25TV_REGISTER_KEY_ID;

+ (jint)ST25TV_NUMBER_OF_REGISTERS;

+ (jint)ST25TV_KILL_PASSWORD_ID;

+ (jint)ST25TV_UNTRACEABLE_MODE_PASSWORD_ID;

+ (jint)ST25TV_AREA1_PASSWORD_ID;

+ (jint)ST25TV_AREA2_PASSWORD_ID;

+ (jint)ST25TV_CONFIGURATION_PASSWORD_ID;

+ (jint)ST25TV_NUMBER_OF_PASSWORDS;

+ (jint)EAS_TELEGRAM_BLOCK_OFFSET;

+ (jint)EAS_TELEGRAM_MAX_LENGTH;

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                  withByteArray:(IOSByteArray *)uid;

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                  withByteArray:(IOSByteArray *)uid
                                                    withBoolean:(jboolean)checkEasStatus;

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                  withByteArray:(IOSByteArray *)uid
                                                    withBoolean:(jboolean)checkEasStatus
                                                    withBoolean:(jboolean)sendInitCommands;

- (void)enableCounterWithBoolean:(jboolean)enableCounter;

- (IOSByteArray *)enableEasWithByte:(jbyte)easIdMask
                      withByteArray:(IOSByteArray *)easId
                           withByte:(jbyte)flag;

- (void)enableUntraceableModeWithByteArray:(IOSByteArray *)password;

- (IOSByteArray *)fastInitiateWithByte:(jbyte)flag;

- (IOSByteArray *)fastInventoryInitiatedWithByte:(jbyte)flag;

- (IOSByteArray *)fastInventoryInitiatedWithByte:(jbyte)flag
                                        withByte:(jbyte)maskLength
                                   withByteArray:(IOSByteArray *)maskValue;

- (IOSByteArray *)fastInventoryInitiatedWithByte:(jbyte)flag
                                        withByte:(jbyte)maskLength
                                   withByteArray:(IOSByteArray *)maskValue
                                        withByte:(jbyte)afiField;

- (IOSByteArray *)fastInventoryReadWithByte:(jbyte)flag
                                   withByte:(jbyte)blockAddress
                                   withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)fastInventoryReadWithByte:(jbyte)flag
                                   withByte:(jbyte)maskLength
                              withByteArray:(IOSByteArray *)maskValue
                                   withByte:(jbyte)blockAddress
                                   withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)fastInventoryReadWithByte:(jbyte)flag
                                   withByte:(jbyte)maskLength
                              withByteArray:(IOSByteArray *)maskValue
                                   withByte:(jbyte)afiField
                                   withByte:(jbyte)blockAddress
                                   withByte:(jbyte)nbrOfBlocks;

- (jint)getAreaFromByteAddressWithInt:(jint)address;

- (jint)getAreaOffsetInBlocksWithInt:(jint)area;

- (jint)getAreaOffsetInBytesWithInt:(jint)area;

- (jint)getAreaPasswordLengthWithInt:(jint)area;

- (jint)getAreaSizeInBytesWithInt:(jint)area;

- (jint)getConfigurationPasswordNumber;

- (NSString *)getDecodedCertificateNDA;

- (id<JavaUtilList>)getDynamicRegisterList;

- (jbyte)getKeyIdNDA;

- (jint)getMaxEasTelegramLength;

- (jint)getMaxNumberOfAreas;

- (jint)getNumberOfAreas;

- (jint)getPasswordLengthWithInt:(jint)passwordNumber;

- (jint)getPasswordNumberWithInt:(jint)area;

- (id<JavaUtilList>)getPossibleReadWriteProtectionWithInt:(jint)area;

- (IOSByteArray *)getRandomNumber;

- (IOSByteArray *)getRandomNumberWithByte:(jbyte)flag;

- (ComStSt25sdkTagHelper_ReadWriteProtection *)getReadWriteProtectionWithInt:(jint)area;

- (ComStSt25sdkSTRegister *)getRegisterWithInt:(jint)registerAddress;

- (ComStSt25sdkType5St25tvST25TVRegisterCounterConfiguration *)getRegisterCounterConfiguration;

- (ComStSt25sdkType5St25tvST25TVRegisterCounterValue *)getRegisterCounterValue;

- (ComStSt25sdkType5St25tvST25TVRegisterEasSecurityActivation *)getRegisterEasSecurityActivation;

- (id<JavaUtilList>)getRegisterList;

- (ComStSt25sdkType5St25tvST25TVRegisterTamperConfiguration *)getRegisterTamperConfiguration;

+ (id<JavaUtilList>)getSt25tvExtraFeatureList;

- (ComStSt25sdkUntraceableModeInterface_UntraceableModeDefaultSettings *)getUntraceableModeDefaultSettings;

- (ComStSt25sdkUntraceableModeInterface_UntraceableModePolicy *)getUntraceableModePolicy;

- (IOSByteArray *)initiateWithByte:(jbyte)flag OBJC_METHOD_FAMILY_NONE;

- (IOSByteArray *)inventoryInitiatedWithByte:(jbyte)flag;

- (IOSByteArray *)inventoryInitiatedWithByte:(jbyte)flag
                                    withByte:(jbyte)maskLength
                               withByteArray:(IOSByteArray *)maskValue;

- (IOSByteArray *)inventoryInitiatedWithByte:(jbyte)flag
                                    withByte:(jbyte)maskLength
                               withByteArray:(IOSByteArray *)maskValue
                                    withByte:(jbyte)afiField;

- (IOSByteArray *)inventoryReadWithByte:(jbyte)flag
                               withByte:(jbyte)blockAddress
                               withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)inventoryReadWithByte:(jbyte)flag
                               withByte:(jbyte)maskLength
                          withByteArray:(IOSByteArray *)maskValue
                               withByte:(jbyte)blockAddress
                               withByte:(jbyte)nbrOfBlocks;

- (IOSByteArray *)inventoryReadWithByte:(jbyte)flag
                               withByte:(jbyte)maskLength
                          withByteArray:(IOSByteArray *)maskValue
                               withByte:(jbyte)afiField
                               withByte:(jbyte)blockAddress
                               withByte:(jbyte)nbrOfBlocks;

- (jboolean)isConfigurationLocked;

- (jboolean)isCounterEnabled;

- (jboolean)isEasEnabled;

- (jboolean)isSignatureOkNDA;

- (jboolean)isTamperDetectSupported;

- (jbyte)killWithByteArray:(IOSByteArray *)unencryptedKillPassword;

- (void)lockConfiguration;

- (void)lockEas;

- (void)lockEasWithByte:(jbyte)flag;

- (jbyte)lockKill;

- (void)presentPasswordWithInt:(jint)passwordNumber
                 withByteArray:(IOSByteArray *)password;

- (void)presentPasswordWithInt:(jint)passwordNumber
                 withByteArray:(IOSByteArray *)password
                      withByte:(jbyte)flag;

- (IOSByteArray *)readConfigWithInt:(jint)configId;

- (jint)readCounterValue;

- (jint)readEasId;

- (NSString *)readEasTelegram;

- (IOSByteArray *)readSignatureNDA;

- (void)refreshRegistersStatus;

- (void)resetCounter;

- (void)resetEas;

- (void)resetEasWithByte:(jbyte)flag;

- (void)setEas;

- (void)setEasWithByte:(jbyte)flag;

- (void)setNumberOfAreasWithInt:(jint)nbOfAreas;

- (void)setPasswordNumberWithInt:(jint)area
                         withInt:(jint)passwordNumber;

- (void)setReadWriteProtectionWithInt:(jint)area
withComStSt25sdkTagHelper_ReadWriteProtection:(ComStSt25sdkTagHelper_ReadWriteProtection *)protection;

- (void)setReadWriteProtectionWithInt:(jint)area
withComStSt25sdkTagHelper_ReadWriteProtection:(ComStSt25sdkTagHelper_ReadWriteProtection *)protection
                        withByteArray:(IOSByteArray *)password;

- (void)setUntraceableModeDefaultSettingsWithComStSt25sdkUntraceableModeInterface_UntraceableModeDefaultSettings:(ComStSt25sdkUntraceableModeInterface_UntraceableModeDefaultSettings *)mode;

- (void)setUntraceableModePolicyWithComStSt25sdkUntraceableModeInterface_UntraceableModePolicy:(ComStSt25sdkUntraceableModeInterface_UntraceableModePolicy *)mode;

- (void)toggleUntraceableModeWithByteArray:(IOSByteArray *)password
                                  withByte:(jbyte)flag;

- (jbyte)writeConfigWithInt:(jint)configId
                   withByte:(jbyte)value;

- (void)writeEasConfigWithByte:(jbyte)config;

- (void)writeEasConfigWithByte:(jbyte)config
                      withByte:(jbyte)flag;

- (void)writeEasIdWithInt:(jint)easId;

- (void)writeEasIdWithInt:(jint)easId
                 withByte:(jbyte)flag;

- (void)writeEasSecurityConfigurationWithBoolean:(jboolean)isEasWriteProtected;

- (void)writeEasTelegramWithNSString:(NSString *)telegram;

- (void)writeEasTelegramWithNSString:(NSString *)telegram
                            withByte:(jbyte)flag;

- (jbyte)writeKillWithByteArray:(IOSByteArray *)unencryptedKillPassword;

- (void)writePasswordWithInt:(jint)passwordNumber
               withByteArray:(IOSByteArray *)newPassword;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType5St25tvST25TVTag)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_REGISTER_AREA1_SECURITY_ATTRIBUTE(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_REGISTER_AREA1_SECURITY_ATTRIBUTE 0
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_REGISTER_AREA1_SECURITY_ATTRIBUTE, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_REGISTER_AREA2_SECURITY_ATTRIBUTE(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_REGISTER_AREA2_SECURITY_ATTRIBUTE 1
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_REGISTER_AREA2_SECURITY_ATTRIBUTE, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_REGISTER_EAS_SECURITY_ACTIVATION(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_REGISTER_EAS_SECURITY_ACTIVATION 2
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_REGISTER_EAS_SECURITY_ACTIVATION, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_REGISTER_WRITE_COUNTER_CONFIGURATION(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_REGISTER_WRITE_COUNTER_CONFIGURATION 3
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_REGISTER_WRITE_COUNTER_CONFIGURATION, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_REGISTER_COUNTER_READ(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_REGISTER_COUNTER_READ 4
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_REGISTER_COUNTER_READ, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_REGISTER_COUNTER_READ_LENGTH(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_REGISTER_COUNTER_READ_LENGTH 2
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_REGISTER_COUNTER_READ_LENGTH, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_REGISTER_TAMPER_CONFIGURATION(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_REGISTER_TAMPER_CONFIGURATION 5
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_REGISTER_TAMPER_CONFIGURATION, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_REGISTER_LOCK_CONFIGURATION(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_REGISTER_LOCK_CONFIGURATION 6
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_REGISTER_LOCK_CONFIGURATION, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_REGISTER_KEY_ID(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_REGISTER_KEY_ID 7
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_REGISTER_KEY_ID, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_NUMBER_OF_REGISTERS(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_NUMBER_OF_REGISTERS 8
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_NUMBER_OF_REGISTERS, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_KILL_PASSWORD_ID(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_KILL_PASSWORD_ID 0
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_KILL_PASSWORD_ID, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_UNTRACEABLE_MODE_PASSWORD_ID(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_UNTRACEABLE_MODE_PASSWORD_ID 0
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_UNTRACEABLE_MODE_PASSWORD_ID, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_AREA1_PASSWORD_ID(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_AREA1_PASSWORD_ID 1
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_AREA1_PASSWORD_ID, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_AREA2_PASSWORD_ID(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_AREA2_PASSWORD_ID 2
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_AREA2_PASSWORD_ID, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_CONFIGURATION_PASSWORD_ID(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_CONFIGURATION_PASSWORD_ID 3
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_CONFIGURATION_PASSWORD_ID, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_ST25TV_NUMBER_OF_PASSWORDS(void);
#define ComStSt25sdkType5St25tvST25TVTag_ST25TV_NUMBER_OF_PASSWORDS 4
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, ST25TV_NUMBER_OF_PASSWORDS, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_EAS_TELEGRAM_BLOCK_OFFSET(void);
#define ComStSt25sdkType5St25tvST25TVTag_EAS_TELEGRAM_BLOCK_OFFSET 248
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, EAS_TELEGRAM_BLOCK_OFFSET, jint)

inline jint ComStSt25sdkType5St25tvST25TVTag_get_EAS_TELEGRAM_MAX_LENGTH(void);
#define ComStSt25sdkType5St25tvST25TVTag_EAS_TELEGRAM_MAX_LENGTH 32
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25tvST25TVTag, EAS_TELEGRAM_MAX_LENGTH, jint)

FOUNDATION_EXPORT id<JavaUtilList> ComStSt25sdkType5St25tvST25TVTag_getSt25tvExtraFeatureList(void);

FOUNDATION_EXPORT void ComStSt25sdkType5St25tvST25TVTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(ComStSt25sdkType5St25tvST25TVTag *self, id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkType5St25tvST25TVTag *new_ComStSt25sdkType5St25tvST25TVTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType5St25tvST25TVTag *create_ComStSt25sdkType5St25tvST25TVTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT void ComStSt25sdkType5St25tvST25TVTag_initWithComStSt25sdkRFReaderInterface_withByteArray_withBoolean_(ComStSt25sdkType5St25tvST25TVTag *self, id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid, jboolean checkEasStatus);

FOUNDATION_EXPORT ComStSt25sdkType5St25tvST25TVTag *new_ComStSt25sdkType5St25tvST25TVTag_initWithComStSt25sdkRFReaderInterface_withByteArray_withBoolean_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid, jboolean checkEasStatus) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType5St25tvST25TVTag *create_ComStSt25sdkType5St25tvST25TVTag_initWithComStSt25sdkRFReaderInterface_withByteArray_withBoolean_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid, jboolean checkEasStatus);

FOUNDATION_EXPORT void ComStSt25sdkType5St25tvST25TVTag_initWithComStSt25sdkRFReaderInterface_withByteArray_withBoolean_withBoolean_(ComStSt25sdkType5St25tvST25TVTag *self, id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid, jboolean checkEasStatus, jboolean sendInitCommands);

FOUNDATION_EXPORT ComStSt25sdkType5St25tvST25TVTag *new_ComStSt25sdkType5St25tvST25TVTag_initWithComStSt25sdkRFReaderInterface_withByteArray_withBoolean_withBoolean_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid, jboolean checkEasStatus, jboolean sendInitCommands) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType5St25tvST25TVTag *create_ComStSt25sdkType5St25tvST25TVTag_initWithComStSt25sdkRFReaderInterface_withByteArray_withBoolean_withBoolean_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid, jboolean checkEasStatus, jboolean sendInitCommands);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType5St25tvST25TVTag)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType5St25tvST25TVTag")
