//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type5/st25tv/ST25TVRegisterArea1SecurityAttribute.java
//

#include "J2ObjC_source.h"
#include "com/st/st25sdk/STException.h"
#include "com/st/st25sdk/STRegister.h"
#include "com/st/st25sdk/TagHelper.h"
#include "com/st/st25sdk/command/Iso15693CustomCommand.h"
#include "com/st/st25sdk/type5/STType5Register.h"
#include "com/st/st25sdk/type5/st25tv/ST25TVRegisterArea1SecurityAttribute.h"
#include "java/util/ArrayList.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute ()

- (jint)getRawSecurityStatusValueWithComStSt25sdkTagHelper_ReadWriteProtection:(ComStSt25sdkTagHelper_ReadWriteProtection *)readWriteProtection;

- (ComStSt25sdkTagHelper_ReadWriteProtection *)getAreaSecurityStatusWithInt:(jint)value;

@end

__attribute__((unused)) static jint ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_getRawSecurityStatusValueWithComStSt25sdkTagHelper_ReadWriteProtection_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *self, ComStSt25sdkTagHelper_ReadWriteProtection *readWriteProtection);

__attribute__((unused)) static ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_getAreaSecurityStatusWithInt_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *self, jint value);

@interface ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1 : JavaUtilArrayList

- (instancetype)initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute:(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *)outer$;

- (ComStSt25sdkSTRegister_STRegisterField *)getWithInt:(jint)arg0;

- (ComStSt25sdkSTRegister_STRegisterField *)removeWithInt:(jint)arg0;

- (ComStSt25sdkSTRegister_STRegisterField *)setWithInt:(jint)arg0
                                                withId:(ComStSt25sdkSTRegister_STRegisterField *)arg1;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1)

__attribute__((unused)) static void ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1_initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1 *self, ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *outer$);

__attribute__((unused)) static ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1 *new_ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1_initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1 *create_ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1_initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *outer$);

@implementation ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute

+ (ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *)newInstanceWithComStSt25sdkCommandIso15693CustomCommand:(ComStSt25sdkCommandIso15693CustomCommand *)iso15693CustomCommand
                                                                                                                 withInt:(jint)registerAddress {
  return ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_newInstanceWithComStSt25sdkCommandIso15693CustomCommand_withInt_(iso15693CustomCommand, registerAddress);
}

- (instancetype)initWithComStSt25sdkCommandIso15693CustomCommand:(ComStSt25sdkCommandIso15693CustomCommand *)iso15693CustomCommand
                                                         withInt:(jint)registerAddress
                                                    withNSString:(NSString *)registerName
                                                    withNSString:(NSString *)registerContentDescription
                 withComStSt25sdkSTRegister_RegisterAccessRights:(ComStSt25sdkSTRegister_RegisterAccessRights *)registerAccessRights
                     withComStSt25sdkSTRegister_RegisterDataSize:(ComStSt25sdkSTRegister_RegisterDataSize *)registerDataSize {
  ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(self, iso15693CustomCommand, registerAddress, registerName, registerContentDescription, registerAccessRights, registerDataSize);
  return self;
}

- (ComStSt25sdkTagHelper_ReadWriteProtection *)getArea1ReadWriteProtection {
  ComStSt25sdkTagHelper_ReadWriteProtection *readWriteProtection;
  jint fieldValue = [((ComStSt25sdkSTRegister_STRegisterField *) nil_chk([self getRegisterFieldWithNSString:@"RW_PROTECTION_A1"])) getValue];
  readWriteProtection = ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_getAreaSecurityStatusWithInt_(self, fieldValue);
  return readWriteProtection;
}

- (jboolean)isMemoryConfiguredInSingleArea {
  jboolean isMemoryConfiguredInSingleArea;
  jint fieldValue = [((ComStSt25sdkSTRegister_STRegisterField *) nil_chk([self getRegisterFieldWithNSString:@"MEM_ORG"])) getValue];
  isMemoryConfiguredInSingleArea = (fieldValue == 1);
  return isMemoryConfiguredInSingleArea;
}

- (void)setArea1ReadWriteProtectionWithComStSt25sdkTagHelper_ReadWriteProtection:(ComStSt25sdkTagHelper_ReadWriteProtection *)area1ReadWriteProtection {
  jint fieldValue = ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_getRawSecurityStatusValueWithComStSt25sdkTagHelper_ReadWriteProtection_(self, area1ReadWriteProtection);
  [((ComStSt25sdkSTRegister_STRegisterField *) nil_chk([self getRegisterFieldWithNSString:@"RW_PROTECTION_A1"])) setValueWithInt:fieldValue];
}

- (void)setIsMemoryConfiguredInSingleAreaWithBoolean:(jboolean)isMemoryConfiguredInSingleArea {
  jint fieldValue = isMemoryConfiguredInSingleArea ? 1 : 0;
  [((ComStSt25sdkSTRegister_STRegisterField *) nil_chk([self getRegisterFieldWithNSString:@"MEM_ORG"])) setValueWithInt:fieldValue];
}

- (jint)getRawSecurityStatusValueWithComStSt25sdkTagHelper_ReadWriteProtection:(ComStSt25sdkTagHelper_ReadWriteProtection *)readWriteProtection {
  return ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_getRawSecurityStatusValueWithComStSt25sdkTagHelper_ReadWriteProtection_(self, readWriteProtection);
}

- (ComStSt25sdkTagHelper_ReadWriteProtection *)getAreaSecurityStatusWithInt:(jint)value {
  return ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_getAreaSecurityStatusWithInt_(self, value);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LComStSt25sdkTagHelper_ReadWriteProtection;", 0x1, -1, -1, 3, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, 3, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, 3, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, 3, -1, -1, -1 },
    { NULL, "I", 0x2, 8, 5, 3, -1, -1, -1 },
    { NULL, "LComStSt25sdkTagHelper_ReadWriteProtection;", 0x2, 9, 10, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(newInstanceWithComStSt25sdkCommandIso15693CustomCommand:withInt:);
  methods[1].selector = @selector(initWithComStSt25sdkCommandIso15693CustomCommand:withInt:withNSString:withNSString:withComStSt25sdkSTRegister_RegisterAccessRights:withComStSt25sdkSTRegister_RegisterDataSize:);
  methods[2].selector = @selector(getArea1ReadWriteProtection);
  methods[3].selector = @selector(isMemoryConfiguredInSingleArea);
  methods[4].selector = @selector(setArea1ReadWriteProtectionWithComStSt25sdkTagHelper_ReadWriteProtection:);
  methods[5].selector = @selector(setIsMemoryConfiguredInSingleAreaWithBoolean:);
  methods[6].selector = @selector(getRawSecurityStatusValueWithComStSt25sdkTagHelper_ReadWriteProtection:);
  methods[7].selector = @selector(getAreaSecurityStatusWithInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "newInstance", "LComStSt25sdkCommandIso15693CustomCommand;I", "LComStSt25sdkCommandIso15693CustomCommand;ILNSString;LNSString;LComStSt25sdkSTRegister_RegisterAccessRights;LComStSt25sdkSTRegister_RegisterDataSize;", "LComStSt25sdkSTException;", "setArea1ReadWriteProtection", "LComStSt25sdkTagHelper_ReadWriteProtection;", "setIsMemoryConfiguredInSingleArea", "Z", "getRawSecurityStatusValue", "getAreaSecurityStatus", "I" };
  static const J2ObjcClassInfo _ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute = { "ST25TVRegisterArea1SecurityAttribute", "com.st.st25sdk.type5.st25tv", ptrTable, methods, NULL, 7, 0x1, 8, 0, -1, -1, -1, -1, -1 };
  return &_ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute;
}

@end

ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_newInstanceWithComStSt25sdkCommandIso15693CustomCommand_withInt_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint registerAddress) {
  ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_initialize();
  NSString *registerName = @"Area1SecurityAttribute";
  NSString *registerContentDescription = @"Bits [1:0] : Area 1 access rights\nBit  [2]   : Memory organization:\n              0: two areas\n              1: single area\nBits [7:3] : RFU";
  return new_ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(iso15693CustomCommand, registerAddress, registerName, registerContentDescription, JreLoadEnum(ComStSt25sdkSTRegister_RegisterAccessRights, REGISTER_READ_WRITE), JreLoadEnum(ComStSt25sdkSTRegister_RegisterDataSize, REGISTER_DATA_ON_8_BITS));
}

void ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *self, ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize) {
  ComStSt25sdkType5STType5Register_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(self, iso15693CustomCommand, registerAddress, registerName, registerContentDescription, registerAccessRights, registerDataSize);
  [self createFieldHashWithJavaUtilList:new_ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1_initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_(self)];
}

ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *new_ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize) {
  J2OBJC_NEW_IMPL(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute, initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_, iso15693CustomCommand, registerAddress, registerName, registerContentDescription, registerAccessRights, registerDataSize)
}

ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *create_ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize) {
  J2OBJC_CREATE_IMPL(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute, initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_, iso15693CustomCommand, registerAddress, registerName, registerContentDescription, registerAccessRights, registerDataSize)
}

jint ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_getRawSecurityStatusValueWithComStSt25sdkTagHelper_ReadWriteProtection_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *self, ComStSt25sdkTagHelper_ReadWriteProtection *readWriteProtection) {
  jint value;
  switch ([readWriteProtection ordinal]) {
    case ComStSt25sdkTagHelper_ReadWriteProtection_Enum_READABLE_AND_WRITABLE:
    value = (jint) 0x00;
    break;
    case ComStSt25sdkTagHelper_ReadWriteProtection_Enum_READABLE_AND_WRITE_PROTECTED_BY_PWD:
    value = (jint) 0x01;
    break;
    case ComStSt25sdkTagHelper_ReadWriteProtection_Enum_READ_AND_WRITE_PROTECTED_BY_PWD:
    value = (jint) 0x02;
    break;
    case ComStSt25sdkTagHelper_ReadWriteProtection_Enum_READ_PROTECTED_BY_PWD_AND_WRITE_IMPOSSIBLE:
    value = (jint) 0x03;
    break;
    default:
    @throw new_ComStSt25sdkSTException_initWithComStSt25sdkSTException_STExceptionCode_(JreLoadEnum(ComStSt25sdkSTException_STExceptionCode, BAD_PARAMETER));
  }
  return value;
}

ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_getAreaSecurityStatusWithInt_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *self, jint value) {
  ComStSt25sdkTagHelper_ReadWriteProtection *readWriteProtection = JreLoadEnum(ComStSt25sdkTagHelper_ReadWriteProtection, READABLE_AND_WRITABLE);
  switch (value) {
    case (jint) 0x0:
    readWriteProtection = JreLoadEnum(ComStSt25sdkTagHelper_ReadWriteProtection, READABLE_AND_WRITABLE);
    break;
    case (jint) 0x1:
    readWriteProtection = JreLoadEnum(ComStSt25sdkTagHelper_ReadWriteProtection, READABLE_AND_WRITE_PROTECTED_BY_PWD);
    break;
    case (jint) 0x2:
    readWriteProtection = JreLoadEnum(ComStSt25sdkTagHelper_ReadWriteProtection, READ_AND_WRITE_PROTECTED_BY_PWD);
    break;
    case (jint) 0x3:
    readWriteProtection = JreLoadEnum(ComStSt25sdkTagHelper_ReadWriteProtection, READ_PROTECTED_BY_PWD_AND_WRITE_IMPOSSIBLE);
    break;
  }
  return readWriteProtection;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute)

@implementation ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1

- (instancetype)initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute:(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *)outer$ {
  ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1_initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_(self, outer$);
  return self;
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute;", "initWithComStSt25sdkCommandIso15693CustomCommand:withInt:withNSString:withNSString:withComStSt25sdkSTRegister_RegisterAccessRights:withComStSt25sdkSTRegister_RegisterDataSize:", "Ljava/util/ArrayList<Lcom/st/st25sdk/STRegister$STRegisterField;>;" };
  static const J2ObjcClassInfo _ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1 = { "", "com.st.st25sdk.type5.st25tv", ptrTable, methods, NULL, 7, 0x8010, 1, 0, 0, -1, 1, 2, -1 };
  return &_ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1;
}

@end

void ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1_initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1 *self, ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *outer$) {
  JavaUtilArrayList_init(self);
  {
    [self addWithId:new_ComStSt25sdkSTRegister_STRegisterField_initWithComStSt25sdkSTRegister_withNSString_withNSString_withInt_(outer$, @"RW_PROTECTION_A1", @"Area 1 access rights:\n00 : Read and Write always allowed\n01 : Read allowed, Write is password-protected\n10 : Read and Write are password-protected\n11 : Read password-protected, Write forbidden\n", (jint) 0x03)];
    [self addWithId:new_ComStSt25sdkSTRegister_STRegisterField_initWithComStSt25sdkSTRegister_withNSString_withNSString_withInt_(outer$, @"MEM_ORG", @"User memory split:\n0 : two areas\n1 : single area\n", (jint) 0x04)];
    [self addWithId:new_ComStSt25sdkSTRegister_STRegisterField_initWithComStSt25sdkSTRegister_withNSString_withNSString_withInt_(outer$, @"RFU", @"RFU", (jint) 0xF8)];
  }
}

ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1 *new_ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1_initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *outer$) {
  J2OBJC_NEW_IMPL(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1, initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_, outer$)
}

ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1 *create_ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1_initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute *outer$) {
  J2OBJC_CREATE_IMPL(ComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_1, initWithComStSt25sdkType5St25tvST25TVRegisterArea1SecurityAttribute_, outer$)
}
