//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type4a/m24srtahighdensity/M24SRTag.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensityM24SRTag")
#ifdef RESTRICT_ComStSt25sdkType4aM24srtahighdensityM24SRTag
#define INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensityM24SRTag 0
#else
#define INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensityM24SRTag 1
#endif
#undef RESTRICT_ComStSt25sdkType4aM24srtahighdensityM24SRTag

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType4aM24srtahighdensityM24SRTag_) && (INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensityM24SRTag || defined(INCLUDE_ComStSt25sdkType4aM24srtahighdensityM24SRTag))
#define ComStSt25sdkType4aM24srtahighdensityM24SRTag_

#define RESTRICT_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag 1
#define INCLUDE_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag 1
#include "com/st/st25sdk/type4a/m24srtahighdensity/M24SRTAHighDensityTag.h"

#define RESTRICT_ComStSt25sdkType4aSTType4GpoInterface 1
#define INCLUDE_ComStSt25sdkType4aSTType4GpoInterface 1
#include "com/st/st25sdk/type4a/STType4GpoInterface.h"

@class ComStSt25sdkType4aSTType4GpoInterface_GpoMode;
@class IOSByteArray;
@protocol ComStSt25sdkRFReaderInterface;
@protocol JavaUtilList;

@interface ComStSt25sdkType4aM24srtahighdensityM24SRTag : ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag < ComStSt25sdkType4aSTType4GpoInterface > {
 @public
  id<JavaUtilList> mSupportedGpoModes_;
}

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                  withByteArray:(IOSByteArray *)uid;

- (jbyte)getGpo;

- (ComStSt25sdkType4aSTType4GpoInterface_GpoMode *)getGpoModeWithByte:(jbyte)gpoConfig;

- (jbyte)getI2CProtected;

- (jbyte)getI2CWatchdog;

- (jbyte)getRfEnabled;

- (id<JavaUtilList>)getSupportedGpoModes;

- (jboolean)isGpoConfigurableByRf;

- (jboolean)isGpoInInterruptedMode;

- (jboolean)isGpoInStateControlMode;

- (jboolean)isGpoLocked;

- (void)lockGpo;

- (void)lockGpoWithByte:(jbyte)value;

- (void)sendInterruptCommand;

- (void)setGpoWithByte:(jbyte)value;

- (void)setGpoModeWithComStSt25sdkType4aSTType4GpoInterface_GpoMode:(ComStSt25sdkType4aSTType4GpoInterface_GpoMode *)mode;

- (void)setStateControlCommandWithInt:(jint)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType4aM24srtahighdensityM24SRTag)

J2OBJC_FIELD_SETTER(ComStSt25sdkType4aM24srtahighdensityM24SRTag, mSupportedGpoModes_, id<JavaUtilList>)

FOUNDATION_EXPORT void ComStSt25sdkType4aM24srtahighdensityM24SRTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(ComStSt25sdkType4aM24srtahighdensityM24SRTag *self, id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkType4aM24srtahighdensityM24SRTag *new_ComStSt25sdkType4aM24srtahighdensityM24SRTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType4aM24srtahighdensityM24SRTag *create_ComStSt25sdkType4aM24srtahighdensityM24SRTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType4aM24srtahighdensityM24SRTag)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensityM24SRTag")
