//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type4a/m24srtahighdensity/M24SRTAHighDensityTag.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag")
#ifdef RESTRICT_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag
#define INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag 0
#else
#define INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag 1
#endif
#undef RESTRICT_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag_) && (INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag || defined(INCLUDE_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag))
#define ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag_

#define RESTRICT_ComStSt25sdkType4aSTType4MultiAreaTag 1
#define INCLUDE_ComStSt25sdkType4aSTType4MultiAreaTag 1
#include "com/st/st25sdk/type4a/STType4MultiAreaTag.h"

#define RESTRICT_ComStSt25sdkCacheInterface 1
#define INCLUDE_ComStSt25sdkCacheInterface 1
#include "com/st/st25sdk/CacheInterface.h"

#define RESTRICT_ComStSt25sdkMultiAreaInterface 1
#define INCLUDE_ComStSt25sdkMultiAreaInterface 1
#include "com/st/st25sdk/MultiAreaInterface.h"

@class ComStSt25sdkNdefNDEFMsg;
@class IOSByteArray;
@protocol ComStSt25sdkRFReaderInterface;

@interface ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag : ComStSt25sdkType4aSTType4MultiAreaTag < ComStSt25sdkCacheInterface, ComStSt25sdkMultiAreaInterface >

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                  withByteArray:(IOSByteArray *)uid;

- (void)_writeNdefMessageWithInt:(jint)fileId
     withComStSt25sdkNdefNDEFMsg:(ComStSt25sdkNdefNDEFMsg *)msg;

- (jint)getMaxNumberOfAreas;

- (jint)getMaxNumberOfFiles;

- (jint)getNbrOfFiles;

- (jint)getNDEFFileNumber;

- (void)setNbrOfFilesWithInt:(jint)fileNbr;

- (void)setNumberOfAreasWithInt:(jint)nbOfAreas;

- (void)writeNdefMessageWithInt:(jint)fileId
    withComStSt25sdkNdefNDEFMsg:(ComStSt25sdkNdefNDEFMsg *)msg;

- (void)writeNdefMessageWithInt:(jint)fileId
    withComStSt25sdkNdefNDEFMsg:(ComStSt25sdkNdefNDEFMsg *)msg
                  withByteArray:(IOSByteArray *)writePassword;

- (void)writeNdefMessageWithComStSt25sdkNdefNDEFMsg:(ComStSt25sdkNdefNDEFMsg *)msg;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag)

FOUNDATION_EXPORT void ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag *self, id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag *new_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag *create_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensityM24SRTAHighDensityTag")
