//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type4a/m24srtahighdensity/SysFileM24SR.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensitySysFileM24SR")
#ifdef RESTRICT_ComStSt25sdkType4aM24srtahighdensitySysFileM24SR
#define INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensitySysFileM24SR 0
#else
#define INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensitySysFileM24SR 1
#endif
#undef RESTRICT_ComStSt25sdkType4aM24srtahighdensitySysFileM24SR

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_) && (INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensitySysFileM24SR || defined(INCLUDE_ComStSt25sdkType4aM24srtahighdensitySysFileM24SR))
#define ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_

#define RESTRICT_ComStSt25sdkType4aM24srtahighdensitySysFileM24SRTAHighDensity 1
#define INCLUDE_ComStSt25sdkType4aM24srtahighdensitySysFileM24SRTAHighDensity 1
#include "com/st/st25sdk/type4a/m24srtahighdensity/SysFileM24SRTAHighDensity.h"

@class ComStSt25sdkCommandType4Command;
@class IOSByteArray;

@interface ComStSt25sdkType4aM24srtahighdensitySysFileM24SR : ComStSt25sdkType4aM24srtahighdensitySysFileM24SRTAHighDensity {
 @public
  jbyte mI2CProtected_;
  jbyte mI2CWatchdog_;
  jbyte mReservedSysByte_;
  jbyte mGpo_;
  jbyte mRFEnabled_;
}
@property (readonly, class) jbyte I2C_PROTECTED_OFFSET NS_SWIFT_NAME(I2C_PROTECTED_OFFSET);
@property (readonly, class) jbyte I2C_WATCHDOG_OFFSET NS_SWIFT_NAME(I2C_WATCHDOG_OFFSET);
@property (readonly, class) jbyte I2C_GPO_OFFSET NS_SWIFT_NAME(I2C_GPO_OFFSET);
@property (readonly, class) jbyte I2C_RF_ENABLE_OFFSET NS_SWIFT_NAME(I2C_RF_ENABLE_OFFSET);

+ (jbyte)I2C_PROTECTED_OFFSET;

+ (jbyte)I2C_WATCHDOG_OFFSET;

+ (jbyte)I2C_GPO_OFFSET;

+ (jbyte)I2C_RF_ENABLE_OFFSET;

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkCommandType4Command:(ComStSt25sdkCommandType4Command *)type4Command;

- (jbyte)getGpo;

- (jbyte)getI2CProtected;

- (jbyte)getI2CWatchdog;

- (jint)getNDEFFileNumber;

- (jbyte)getRfEnabled;

#pragma mark Protected

- (void)parseSysFileWithByteArray:(IOSByteArray *)buffer;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType4aM24srtahighdensitySysFileM24SR)

inline jbyte ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_get_I2C_PROTECTED_OFFSET(void);
#define ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_I2C_PROTECTED_OFFSET 2
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType4aM24srtahighdensitySysFileM24SR, I2C_PROTECTED_OFFSET, jbyte)

inline jbyte ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_get_I2C_WATCHDOG_OFFSET(void);
#define ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_I2C_WATCHDOG_OFFSET 3
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType4aM24srtahighdensitySysFileM24SR, I2C_WATCHDOG_OFFSET, jbyte)

inline jbyte ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_get_I2C_GPO_OFFSET(void);
#define ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_I2C_GPO_OFFSET 4
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType4aM24srtahighdensitySysFileM24SR, I2C_GPO_OFFSET, jbyte)

inline jbyte ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_get_I2C_RF_ENABLE_OFFSET(void);
#define ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_I2C_RF_ENABLE_OFFSET 6
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType4aM24srtahighdensitySysFileM24SR, I2C_RF_ENABLE_OFFSET, jbyte)

FOUNDATION_EXPORT void ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_initWithComStSt25sdkCommandType4Command_(ComStSt25sdkType4aM24srtahighdensitySysFileM24SR *self, ComStSt25sdkCommandType4Command *type4Command);

FOUNDATION_EXPORT ComStSt25sdkType4aM24srtahighdensitySysFileM24SR *new_ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_initWithComStSt25sdkCommandType4Command_(ComStSt25sdkCommandType4Command *type4Command) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType4aM24srtahighdensitySysFileM24SR *create_ComStSt25sdkType4aM24srtahighdensitySysFileM24SR_initWithComStSt25sdkCommandType4Command_(ComStSt25sdkCommandType4Command *type4Command);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType4aM24srtahighdensitySysFileM24SR)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType4aM24srtahighdensitySysFileM24SR")
