//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type5/SysFileVicinity.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/st/st25sdk/Helper.h"
#include "com/st/st25sdk/STException.h"
#include "com/st/st25sdk/command/VicinityCommand.h"
#include "com/st/st25sdk/type5/SysFile.h"
#include "com/st/st25sdk/type5/SysFileVicinity.h"
#include "java/nio/ByteBuffer.h"
#include "java/util/Arrays.h"

@interface ComStSt25sdkType5SysFileVicinity () {
 @public
  ComStSt25sdkCommandVicinityCommand *mVicinityCommand_;
}

@end

J2OBJC_FIELD_SETTER(ComStSt25sdkType5SysFileVicinity, mVicinityCommand_, ComStSt25sdkCommandVicinityCommand *)

@implementation ComStSt25sdkType5SysFileVicinity

- (instancetype)initWithComStSt25sdkCommandVicinityCommand:(ComStSt25sdkCommandVicinityCommand *)vicinityCommand {
  ComStSt25sdkType5SysFileVicinity_initWithComStSt25sdkCommandVicinityCommand_(self, vicinityCommand);
  return self;
}

- (IOSByteArray *)read {
  if (!mCacheActivated_ || mCacheInvalidated_) {
    IOSByteArray *cmdBuffer;
    cmdBuffer = [((ComStSt25sdkCommandVicinityCommand *) nil_chk(mVicinityCommand_)) getSystemInfo];
    if (IOSByteArray_Get(nil_chk(cmdBuffer), 0) != (jint) 0x00) {
      @throw (new_ComStSt25sdkSTException_initWithComStSt25sdkSTException_STExceptionCode_(JreLoadEnum(ComStSt25sdkSTException_STExceptionCode, CMD_FAILED)));
    }
    mBuffer_ = JavaUtilArrays_copyOfRangeWithByteArray_withInt_withInt_(cmdBuffer, 1, cmdBuffer->size_);
  }
  return mBuffer_;
}

- (void)parseSysFileWithByteArray:(IOSByteArray *)buffer {
  JavaNioByteBuffer *byteBuffer = JavaNioByteBuffer_wrapWithByteArray_(buffer);
  jbyte sysInfoByte = [((JavaNioByteBuffer *) nil_chk(byteBuffer)) get];
  (void) [byteBuffer getWithByteArray:mUid_ withInt:0 withInt:8];
  mUid_ = ComStSt25sdkHelper_reverseByteArrayWithByteArray_(mUid_);
  if ((sysInfoByte & ComStSt25sdkType5SysFile_DSFID_MASK) == ComStSt25sdkType5SysFile_DSFID_MASK) {
    mDSFIDSupported_ = true;
    mDSFID_ = [byteBuffer get];
  }
  else mDSFIDSupported_ = false;
  if ((sysInfoByte & ComStSt25sdkType5SysFile_AFI_MASK) == ComStSt25sdkType5SysFile_AFI_MASK) {
    mAFISupported_ = true;
    mAFI_ = [byteBuffer get];
  }
  else mAFISupported_ = false;
  if ((sysInfoByte & ComStSt25sdkType5SysFile_VICC_MEM_SIZE_MASK) == ComStSt25sdkType5SysFile_VICC_MEM_SIZE_MASK) {
    mVICCMemSizesupported_ = true;
    mNumberOfBlocks_ = ComStSt25sdkHelper_convertByteToUnsignedIntWithByte_([byteBuffer get]);
    mNumberOfBlocks_ += (JreLShift32(ComStSt25sdkHelper_convertByteToUnsignedIntWithByte_([byteBuffer get]), 8));
    mBlockSize_ = ([byteBuffer get] & (jint) 0x1F) + 1;
  }
  else mVICCMemSizesupported_ = false;
  if ((sysInfoByte & ComStSt25sdkType5SysFile_ICREF_MASK) == ComStSt25sdkType5SysFile_ICREF_MASK) {
    mICRefSupported_ = true;
    mICRef_ = [byteBuffer get];
  }
  else mICRefSupported_ = false;
  mBuffer_ = [byteBuffer array];
  mLength_ = ((IOSByteArray *) nil_chk(mBuffer_))->size_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, 1, -1, -1, -1 },
    { NULL, "V", 0x4, 2, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComStSt25sdkCommandVicinityCommand:);
  methods[1].selector = @selector(read);
  methods[2].selector = @selector(parseSysFileWithByteArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mVicinityCommand_", "LComStSt25sdkCommandVicinityCommand;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComStSt25sdkCommandVicinityCommand;", "LComStSt25sdkSTException;", "parseSysFile", "[B" };
  static const J2ObjcClassInfo _ComStSt25sdkType5SysFileVicinity = { "SysFileVicinity", "com.st.st25sdk.type5", ptrTable, methods, fields, 7, 0x1, 3, 1, -1, -1, -1, -1, -1 };
  return &_ComStSt25sdkType5SysFileVicinity;
}

@end

void ComStSt25sdkType5SysFileVicinity_initWithComStSt25sdkCommandVicinityCommand_(ComStSt25sdkType5SysFileVicinity *self, ComStSt25sdkCommandVicinityCommand *vicinityCommand) {
  ComStSt25sdkType5SysFile_init(self);
  self->mVicinityCommand_ = vicinityCommand;
}

ComStSt25sdkType5SysFileVicinity *new_ComStSt25sdkType5SysFileVicinity_initWithComStSt25sdkCommandVicinityCommand_(ComStSt25sdkCommandVicinityCommand *vicinityCommand) {
  J2OBJC_NEW_IMPL(ComStSt25sdkType5SysFileVicinity, initWithComStSt25sdkCommandVicinityCommand_, vicinityCommand)
}

ComStSt25sdkType5SysFileVicinity *create_ComStSt25sdkType5SysFileVicinity_initWithComStSt25sdkCommandVicinityCommand_(ComStSt25sdkCommandVicinityCommand *vicinityCommand) {
  J2OBJC_CREATE_IMPL(ComStSt25sdkType5SysFileVicinity, initWithComStSt25sdkCommandVicinityCommand_, vicinityCommand)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComStSt25sdkType5SysFileVicinity)
