//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/iso14443b/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkIso14443bPackage_info")
#ifdef RESTRICT_ComStSt25sdkIso14443bPackage_info
#define INCLUDE_ALL_ComStSt25sdkIso14443bPackage_info 0
#else
#define INCLUDE_ALL_ComStSt25sdkIso14443bPackage_info 1
#endif
#undef RESTRICT_ComStSt25sdkIso14443bPackage_info

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkIso14443bPackage_info")
