//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type4a/FileType4.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType4aFileType4")
#ifdef RESTRICT_ComStSt25sdkType4aFileType4
#define INCLUDE_ALL_ComStSt25sdkType4aFileType4 0
#else
#define INCLUDE_ALL_ComStSt25sdkType4aFileType4 1
#endif
#undef RESTRICT_ComStSt25sdkType4aFileType4

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType4aFileType4_) && (INCLUDE_ALL_ComStSt25sdkType4aFileType4 || defined(INCLUDE_ComStSt25sdkType4aFileType4))
#define ComStSt25sdkType4aFileType4_

@class ComStSt25sdkCommandType4Command;
@class IOSByteArray;

@interface ComStSt25sdkType4aFileType4 : NSObject {
 @public
  jint mFileId_;
  jint mFileSize_;
  jbyte mReadAccess_;
  jbyte mWriteAccess_;
  ComStSt25sdkCommandType4Command *mType4Command_;
}

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkCommandType4Command:(ComStSt25sdkCommandType4Command *)type4Command
                                                          withInt:(jint)fileId;

- (instancetype __nonnull)initWithComStSt25sdkCommandType4Command:(ComStSt25sdkCommandType4Command *)type4Command
                                                          withInt:(jint)fileId
                                                          withInt:(jint)size
                                                         withByte:(jbyte)readAccess
                                                         withByte:(jbyte)writeAccess;

- (jint)getFileId;

- (jbyte)getReadAccess;

- (jint)getSize;

- (jbyte)getWriteAccess;

- (IOSByteArray *)readWithInt:(jint)fileOffset
                      withInt:(jint)sizeInBytes;

- (IOSByteArray *)select;

- (IOSByteArray *)selectFile;

- (void)writeWithInt:(jint)offsetInBytes
       withByteArray:(IOSByteArray *)data;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType4aFileType4)

J2OBJC_FIELD_SETTER(ComStSt25sdkType4aFileType4, mType4Command_, ComStSt25sdkCommandType4Command *)

FOUNDATION_EXPORT void ComStSt25sdkType4aFileType4_initWithComStSt25sdkCommandType4Command_withInt_(ComStSt25sdkType4aFileType4 *self, ComStSt25sdkCommandType4Command *type4Command, jint fileId);

FOUNDATION_EXPORT ComStSt25sdkType4aFileType4 *new_ComStSt25sdkType4aFileType4_initWithComStSt25sdkCommandType4Command_withInt_(ComStSt25sdkCommandType4Command *type4Command, jint fileId) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType4aFileType4 *create_ComStSt25sdkType4aFileType4_initWithComStSt25sdkCommandType4Command_withInt_(ComStSt25sdkCommandType4Command *type4Command, jint fileId);

FOUNDATION_EXPORT void ComStSt25sdkType4aFileType4_initWithComStSt25sdkCommandType4Command_withInt_withInt_withByte_withByte_(ComStSt25sdkType4aFileType4 *self, ComStSt25sdkCommandType4Command *type4Command, jint fileId, jint size, jbyte readAccess, jbyte writeAccess);

FOUNDATION_EXPORT ComStSt25sdkType4aFileType4 *new_ComStSt25sdkType4aFileType4_initWithComStSt25sdkCommandType4Command_withInt_withInt_withByte_withByte_(ComStSt25sdkCommandType4Command *type4Command, jint fileId, jint size, jbyte readAccess, jbyte writeAccess) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType4aFileType4 *create_ComStSt25sdkType4aFileType4_initWithComStSt25sdkCommandType4Command_withInt_withInt_withByte_withByte_(ComStSt25sdkCommandType4Command *type4Command, jint fileId, jint size, jbyte readAccess, jbyte writeAccess);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType4aFileType4)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType4aFileType4")
