//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type4a/STType4GpoInterface.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType4aSTType4GpoInterface")
#ifdef RESTRICT_ComStSt25sdkType4aSTType4GpoInterface
#define INCLUDE_ALL_ComStSt25sdkType4aSTType4GpoInterface 0
#else
#define INCLUDE_ALL_ComStSt25sdkType4aSTType4GpoInterface 1
#endif
#undef RESTRICT_ComStSt25sdkType4aSTType4GpoInterface

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType4aSTType4GpoInterface_) && (INCLUDE_ALL_ComStSt25sdkType4aSTType4GpoInterface || defined(INCLUDE_ComStSt25sdkType4aSTType4GpoInterface))
#define ComStSt25sdkType4aSTType4GpoInterface_

@class ComStSt25sdkType4aSTType4GpoInterface_GpoMode;
@protocol JavaUtilList;

@protocol ComStSt25sdkType4aSTType4GpoInterface < JavaObject >

- (ComStSt25sdkType4aSTType4GpoInterface_GpoMode *)getGpoModeWithByte:(jbyte)gpoConfig;

- (void)setGpoModeWithComStSt25sdkType4aSTType4GpoInterface_GpoMode:(ComStSt25sdkType4aSTType4GpoInterface_GpoMode *)mode;

- (id<JavaUtilList>)getSupportedGpoModes;

- (jbyte)getGpo;

- (void)setGpoWithByte:(jbyte)value;

- (void)lockGpoWithByte:(jbyte)value;

- (void)lockGpo;

- (jboolean)isGpoLocked;

- (jboolean)isGpoConfigurableByRf;

- (jboolean)isGpoInInterruptedMode;

- (jboolean)isGpoInStateControlMode;

- (void)sendInterruptCommand;

- (void)setStateControlCommandWithInt:(jint)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType4aSTType4GpoInterface)

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType4aSTType4GpoInterface)

#endif

#if !defined (ComStSt25sdkType4aSTType4GpoInterface_GpoMode_) && (INCLUDE_ALL_ComStSt25sdkType4aSTType4GpoInterface || defined(INCLUDE_ComStSt25sdkType4aSTType4GpoInterface_GpoMode))
#define ComStSt25sdkType4aSTType4GpoInterface_GpoMode_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum) {
  ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum_GPO_NOT_USED = 0,
  ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum_GPO_HIGH_IMPEDANCE = 1,
  ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum_GPO_SESSION_OPENED = 2,
  ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum_GPO_WIP = 3,
  ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum_GPO_MIP = 4,
  ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum_GPO_INTERRUPT = 5,
  ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum_GPO_STATE_CONTROL = 6,
  ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum_GPO_RF_BUSY = 7,
  ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum_GPO_FIELD_DETECT = 8,
};

@interface ComStSt25sdkType4aSTType4GpoInterface_GpoMode : JavaLangEnum

@property (readonly, class, nonnull) ComStSt25sdkType4aSTType4GpoInterface_GpoMode *GPO_NOT_USED NS_SWIFT_NAME(GPO_NOT_USED);
@property (readonly, class, nonnull) ComStSt25sdkType4aSTType4GpoInterface_GpoMode *GPO_HIGH_IMPEDANCE NS_SWIFT_NAME(GPO_HIGH_IMPEDANCE);
@property (readonly, class, nonnull) ComStSt25sdkType4aSTType4GpoInterface_GpoMode *GPO_SESSION_OPENED NS_SWIFT_NAME(GPO_SESSION_OPENED);
@property (readonly, class, nonnull) ComStSt25sdkType4aSTType4GpoInterface_GpoMode *GPO_WIP NS_SWIFT_NAME(GPO_WIP);
@property (readonly, class, nonnull) ComStSt25sdkType4aSTType4GpoInterface_GpoMode *GPO_MIP NS_SWIFT_NAME(GPO_MIP);
@property (readonly, class, nonnull) ComStSt25sdkType4aSTType4GpoInterface_GpoMode *GPO_INTERRUPT NS_SWIFT_NAME(GPO_INTERRUPT);
@property (readonly, class, nonnull) ComStSt25sdkType4aSTType4GpoInterface_GpoMode *GPO_STATE_CONTROL NS_SWIFT_NAME(GPO_STATE_CONTROL);
@property (readonly, class, nonnull) ComStSt25sdkType4aSTType4GpoInterface_GpoMode *GPO_RF_BUSY NS_SWIFT_NAME(GPO_RF_BUSY);
@property (readonly, class, nonnull) ComStSt25sdkType4aSTType4GpoInterface_GpoMode *GPO_FIELD_DETECT NS_SWIFT_NAME(GPO_FIELD_DETECT);
+ (ComStSt25sdkType4aSTType4GpoInterface_GpoMode * __nonnull)GPO_NOT_USED;

+ (ComStSt25sdkType4aSTType4GpoInterface_GpoMode * __nonnull)GPO_HIGH_IMPEDANCE;

+ (ComStSt25sdkType4aSTType4GpoInterface_GpoMode * __nonnull)GPO_SESSION_OPENED;

+ (ComStSt25sdkType4aSTType4GpoInterface_GpoMode * __nonnull)GPO_WIP;

+ (ComStSt25sdkType4aSTType4GpoInterface_GpoMode * __nonnull)GPO_MIP;

+ (ComStSt25sdkType4aSTType4GpoInterface_GpoMode * __nonnull)GPO_INTERRUPT;

+ (ComStSt25sdkType4aSTType4GpoInterface_GpoMode * __nonnull)GPO_STATE_CONTROL;

+ (ComStSt25sdkType4aSTType4GpoInterface_GpoMode * __nonnull)GPO_RF_BUSY;

+ (ComStSt25sdkType4aSTType4GpoInterface_GpoMode * __nonnull)GPO_FIELD_DETECT;

#pragma mark Public

+ (ComStSt25sdkType4aSTType4GpoInterface_GpoMode *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComStSt25sdkType4aSTType4GpoInterface_GpoMode_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ComStSt25sdkType4aSTType4GpoInterface_GpoMode)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_values_[];

inline ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_get_GPO_NOT_USED(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType4aSTType4GpoInterface_GpoMode, GPO_NOT_USED)

inline ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_get_GPO_HIGH_IMPEDANCE(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType4aSTType4GpoInterface_GpoMode, GPO_HIGH_IMPEDANCE)

inline ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_get_GPO_SESSION_OPENED(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType4aSTType4GpoInterface_GpoMode, GPO_SESSION_OPENED)

inline ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_get_GPO_WIP(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType4aSTType4GpoInterface_GpoMode, GPO_WIP)

inline ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_get_GPO_MIP(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType4aSTType4GpoInterface_GpoMode, GPO_MIP)

inline ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_get_GPO_INTERRUPT(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType4aSTType4GpoInterface_GpoMode, GPO_INTERRUPT)

inline ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_get_GPO_STATE_CONTROL(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType4aSTType4GpoInterface_GpoMode, GPO_STATE_CONTROL)

inline ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_get_GPO_RF_BUSY(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType4aSTType4GpoInterface_GpoMode, GPO_RF_BUSY)

inline ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_get_GPO_FIELD_DETECT(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType4aSTType4GpoInterface_GpoMode, GPO_FIELD_DETECT)

FOUNDATION_EXPORT IOSObjectArray *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_values(void);

FOUNDATION_EXPORT ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComStSt25sdkType4aSTType4GpoInterface_GpoMode *ComStSt25sdkType4aSTType4GpoInterface_GpoMode_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType4aSTType4GpoInterface_GpoMode)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType4aSTType4GpoInterface")
