//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type4a/st25ta/ST25TA512BTag.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType4aSt25taST25TA512BTag")
#ifdef RESTRICT_ComStSt25sdkType4aSt25taST25TA512BTag
#define INCLUDE_ALL_ComStSt25sdkType4aSt25taST25TA512BTag 0
#else
#define INCLUDE_ALL_ComStSt25sdkType4aSt25taST25TA512BTag 1
#endif
#undef RESTRICT_ComStSt25sdkType4aSt25taST25TA512BTag

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType4aSt25taST25TA512BTag_) && (INCLUDE_ALL_ComStSt25sdkType4aSt25taST25TA512BTag || defined(INCLUDE_ComStSt25sdkType4aSt25taST25TA512BTag))
#define ComStSt25sdkType4aSt25taST25TA512BTag_

#define RESTRICT_ComStSt25sdkType4aSt25taST25TATag 1
#define INCLUDE_ComStSt25sdkType4aSt25taST25TATag 1
#include "com/st/st25sdk/type4a/st25ta/ST25TATag.h"

#define RESTRICT_ComStSt25sdkSignatureInterface 1
#define INCLUDE_ComStSt25sdkSignatureInterface 1
#include "com/st/st25sdk/SignatureInterface.h"

@class IOSByteArray;
@protocol ComStSt25sdkRFReaderInterface;

@interface ComStSt25sdkType4aSt25taST25TA512BTag : ComStSt25sdkType4aSt25taST25TATag < ComStSt25sdkSignatureInterface >

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                  withByteArray:(IOSByteArray *)uid;

- (NSString *)getDecodedCertificateNDA;

- (jbyte)getKeyIdNDA;

- (jboolean)isSignatureOkNDA;

- (IOSByteArray *)readSignatureNDA;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType4aSt25taST25TA512BTag)

FOUNDATION_EXPORT void ComStSt25sdkType4aSt25taST25TA512BTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(ComStSt25sdkType4aSt25taST25TA512BTag *self, id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkType4aSt25taST25TA512BTag *new_ComStSt25sdkType4aSt25taST25TA512BTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType4aSt25taST25TA512BTag *create_ComStSt25sdkType4aSt25taST25TA512BTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType4aSt25taST25TA512BTag)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType4aSt25taST25TA512BTag")
