//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type4a/st25ta/ST25TAGpoTag.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/st/st25sdk/RFReaderInterface.h"
#include "com/st/st25sdk/TagCache.h"
#include "com/st/st25sdk/command/Type4CustomCommand.h"
#include "com/st/st25sdk/type4a/STSysFileType4.h"
#include "com/st/st25sdk/type4a/STType4GpoInterface.h"
#include "com/st/st25sdk/type4a/st25ta/ST25TAGpoTag.h"
#include "com/st/st25sdk/type4a/st25ta/ST25TATag.h"
#include "com/st/st25sdk/type4a/st25ta/SysFileST25TAGpo.h"
#include "java/util/List.h"

@implementation ComStSt25sdkType4aSt25taST25TAGpoTag

- (instancetype)initWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                        withByteArray:(IOSByteArray *)uid {
  ComStSt25sdkType4aSt25taST25TAGpoTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(self, readerInterface, uid);
  return self;
}

- (jboolean)isGpoConfigurableByRf {
  return [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) isGpoConfigurableByRf];
}

- (ComStSt25sdkType4aSTType4GpoInterface_GpoMode *)getGpoModeWithByte:(jbyte)gpoConfig {
  return [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) getGpoModeWithByte:gpoConfig];
}

- (void)setGpoModeWithComStSt25sdkType4aSTType4GpoInterface_GpoMode:(ComStSt25sdkType4aSTType4GpoInterface_GpoMode *)mode {
  [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) setGpoModeWithComStSt25sdkType4aSTType4GpoInterface_GpoMode:mode];
}

- (id<JavaUtilList>)getSupportedGpoModes {
  return [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) getSupportedGpoModes];
}

- (jbyte)getGpo {
  return [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) getGpo];
}

- (void)setGpoWithByte:(jbyte)value {
  [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) setGpoWithByte:value];
}

- (void)lockGpoWithByte:(jbyte)value {
  [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) lockGpoWithByte:value];
}

- (void)lockGpo {
  [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) lockGpo];
}

- (jboolean)isGpoLocked {
  return [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) isGpoLocked];
}

- (jboolean)isGpoInInterruptedMode {
  return [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) isGpoInInterruptedMode];
}

- (jboolean)isGpoInStateControlMode {
  return [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) isGpoInStateControlMode];
}

- (void)sendInterruptCommand {
  [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) sendInterruptCommand];
}

- (void)setStateControlCommandWithInt:(jint)value {
  [((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) nil_chk(((ComStSt25sdkType4aSt25taSysFileST25TAGpo *) cast_chk(mSysFile_, [ComStSt25sdkType4aSt25taSysFileST25TAGpo class])))) setStateControlCommandWithInt:(jbyte) value];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, 1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComStSt25sdkType4aSTType4GpoInterface_GpoMode;", 0x1, 2, 3, 1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, 1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, 1, 6, -1, -1 },
    { NULL, "B", 0x1, -1, -1, 1, -1, -1, -1 },
    { NULL, "V", 0x1, 7, 3, 1, -1, -1, -1 },
    { NULL, "V", 0x1, 8, 3, 1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, 1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, 1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, 1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 1, -1, -1, -1 },
    { NULL, "V", 0x1, 9, 10, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComStSt25sdkRFReaderInterface:withByteArray:);
  methods[1].selector = @selector(isGpoConfigurableByRf);
  methods[2].selector = @selector(getGpoModeWithByte:);
  methods[3].selector = @selector(setGpoModeWithComStSt25sdkType4aSTType4GpoInterface_GpoMode:);
  methods[4].selector = @selector(getSupportedGpoModes);
  methods[5].selector = @selector(getGpo);
  methods[6].selector = @selector(setGpoWithByte:);
  methods[7].selector = @selector(lockGpoWithByte:);
  methods[8].selector = @selector(lockGpo);
  methods[9].selector = @selector(isGpoLocked);
  methods[10].selector = @selector(isGpoInInterruptedMode);
  methods[11].selector = @selector(isGpoInStateControlMode);
  methods[12].selector = @selector(sendInterruptCommand);
  methods[13].selector = @selector(setStateControlCommandWithInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComStSt25sdkRFReaderInterface;[B", "LComStSt25sdkSTException;", "getGpoMode", "B", "setGpoMode", "LComStSt25sdkType4aSTType4GpoInterface_GpoMode;", "()Ljava/util/List<Lcom/st/st25sdk/type4a/STType4GpoInterface$GpoMode;>;", "setGpo", "lockGpo", "setStateControlCommand", "I" };
  static const J2ObjcClassInfo _ComStSt25sdkType4aSt25taST25TAGpoTag = { "ST25TAGpoTag", "com.st.st25sdk.type4a.st25ta", ptrTable, methods, NULL, 7, 0x1, 14, 0, -1, -1, -1, -1, -1 };
  return &_ComStSt25sdkType4aSt25taST25TAGpoTag;
}

@end

void ComStSt25sdkType4aSt25taST25TAGpoTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(ComStSt25sdkType4aSt25taST25TAGpoTag *self, id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid) {
  ComStSt25sdkType4aSt25taST25TATag_initWithComStSt25sdkRFReaderInterface_withByteArray_(self, readerInterface, uid);
  [((ComStSt25sdkTagCache *) nil_chk(self->mCache_)) removeWithId:self->mSysFile_];
  self->mSysFile_ = new_ComStSt25sdkType4aSt25taSysFileST25TAGpo_initWithComStSt25sdkCommandType4CustomCommand_(self->mSTType4Cmd_);
  [((ComStSt25sdkTagCache *) nil_chk(self->mCache_)) addWithId:self->mSysFile_];
}

ComStSt25sdkType4aSt25taST25TAGpoTag *new_ComStSt25sdkType4aSt25taST25TAGpoTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid) {
  J2OBJC_NEW_IMPL(ComStSt25sdkType4aSt25taST25TAGpoTag, initWithComStSt25sdkRFReaderInterface_withByteArray_, readerInterface, uid)
}

ComStSt25sdkType4aSt25taST25TAGpoTag *create_ComStSt25sdkType4aSt25taST25TAGpoTag_initWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid) {
  J2OBJC_CREATE_IMPL(ComStSt25sdkType4aSt25taST25TAGpoTag, initWithComStSt25sdkRFReaderInterface_withByteArray_, readerInterface, uid)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComStSt25sdkType4aSt25taST25TAGpoTag)
