//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/Crc.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkCrc")
#ifdef RESTRICT_ComStSt25sdkCrc
#define INCLUDE_ALL_ComStSt25sdkCrc 0
#else
#define INCLUDE_ALL_ComStSt25sdkCrc 1
#endif
#undef RESTRICT_ComStSt25sdkCrc

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkCrc_) && (INCLUDE_ALL_ComStSt25sdkCrc || defined(INCLUDE_ComStSt25sdkCrc))
#define ComStSt25sdkCrc_

@class ComStSt25sdkCrcModel;
@class IOSByteArray;
@class JavaIoFile;

@interface ComStSt25sdkCrc : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

+ (IOSByteArray *)computeCrcWithByteArray:(IOSByteArray *)data;

+ (jint)computeCrcIso14443AWithByteArray:(IOSByteArray *)data;

+ (jint)computeCrcIso14443BWithByteArray:(IOSByteArray *)data;

+ (jint)computeCrcIso15693WithByteArray:(IOSByteArray *)data;

+ (jint)computeCrcPicopassWithByteArray:(IOSByteArray *)data;

+ (jlong)CRCWithByteArray:(IOSByteArray *)data;

+ (jlong)CRCWithJavaIoFile:(JavaIoFile *)file;

+ (jint)crc16LsbFirstWithByteArray:(IOSByteArray *)data
                           withInt:(jint)dataLengthToProceed;

#pragma mark Package-Private

+ (jlong)cmTabWithComStSt25sdkCrcModel:(ComStSt25sdkCrcModel *)cm
                               withInt:(jint)index;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkCrc)

FOUNDATION_EXPORT void ComStSt25sdkCrc_init(ComStSt25sdkCrc *self);

FOUNDATION_EXPORT ComStSt25sdkCrc *new_ComStSt25sdkCrc_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkCrc *create_ComStSt25sdkCrc_init(void);

FOUNDATION_EXPORT IOSByteArray *ComStSt25sdkCrc_computeCrcWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT jlong ComStSt25sdkCrc_cmTabWithComStSt25sdkCrcModel_withInt_(ComStSt25sdkCrcModel *cm, jint index);

FOUNDATION_EXPORT jlong ComStSt25sdkCrc_CRCWithJavaIoFile_(JavaIoFile *file);

FOUNDATION_EXPORT jlong ComStSt25sdkCrc_CRCWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT jint ComStSt25sdkCrc_crc16LsbFirstWithByteArray_withInt_(IOSByteArray *data, jint dataLengthToProceed);

FOUNDATION_EXPORT jint ComStSt25sdkCrc_computeCrcIso15693WithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT jint ComStSt25sdkCrc_computeCrcIso14443BWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT jint ComStSt25sdkCrc_computeCrcIso14443AWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT jint ComStSt25sdkCrc_computeCrcPicopassWithByteArray_(IOSByteArray *data);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkCrc)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkCrc")
