//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/CrcModel.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkCrcModel")
#ifdef RESTRICT_ComStSt25sdkCrcModel
#define INCLUDE_ALL_ComStSt25sdkCrcModel 0
#else
#define INCLUDE_ALL_ComStSt25sdkCrcModel 1
#endif
#undef RESTRICT_ComStSt25sdkCrcModel

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkCrcModel_) && (INCLUDE_ALL_ComStSt25sdkCrcModel || defined(INCLUDE_ComStSt25sdkCrcModel))
#define ComStSt25sdkCrcModel_

@interface ComStSt25sdkCrcModel : NSObject {
 @public
  jint width_;
  jboolean refin_;
  jboolean refot_;
  jlong poly_;
  jlong init__;
  jlong xorot_;
  jlong reg_;
}

#pragma mark Package-Private

- (instancetype __nonnull)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkCrcModel)

FOUNDATION_EXPORT void ComStSt25sdkCrcModel_init(ComStSt25sdkCrcModel *self);

FOUNDATION_EXPORT ComStSt25sdkCrcModel *new_ComStSt25sdkCrcModel_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkCrcModel *create_ComStSt25sdkCrcModel_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkCrcModel)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkCrcModel")
