//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/FastTransferModeInterface.java
//

#include "J2ObjC_source.h"
#include "com/st/st25sdk/FastTransferModeInterface.h"

@interface ComStSt25sdkFastTransferModeInterface : NSObject

@end

@implementation ComStSt25sdkFastTransferModeInterface

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "B", 0x401, 0, 1, 2, -1, -1, -1 },
    { NULL, "B", 0x401, 0, 3, 2, -1, -1, -1 },
    { NULL, "B", 0x401, 0, 4, 2, -1, -1, -1 },
    { NULL, "[B", 0x401, 5, 6, 2, -1, -1, -1 },
    { NULL, "[B", 0x401, 5, 7, 2, -1, -1, -1 },
    { NULL, "I", 0x401, -1, -1, 2, -1, -1, -1 },
    { NULL, "B", 0x401, 8, 1, 2, -1, -1, -1 },
    { NULL, "B", 0x401, 8, 3, 2, -1, -1, -1 },
    { NULL, "B", 0x401, 8, 4, 2, -1, -1, -1 },
    { NULL, "[B", 0x401, 9, 6, 2, -1, -1, -1 },
    { NULL, "[B", 0x401, 9, 7, 2, -1, -1, -1 },
    { NULL, "I", 0x401, -1, -1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(writeMailboxMessageWithByteArray:);
  methods[1].selector = @selector(writeMailboxMessageWithInt:withByteArray:);
  methods[2].selector = @selector(writeMailboxMessageWithInt:withByteArray:withByte:);
  methods[3].selector = @selector(readMailboxMessageWithInt:withInt:);
  methods[4].selector = @selector(readMailboxMessageWithInt:withInt:withByte:);
  methods[5].selector = @selector(readMailboxMessageLength);
  methods[6].selector = @selector(fastWriteMailboxMessageWithByteArray:);
  methods[7].selector = @selector(fastWriteMailboxMessageWithInt:withByteArray:);
  methods[8].selector = @selector(fastWriteMailboxMessageWithInt:withByteArray:withByte:);
  methods[9].selector = @selector(fastReadMailboxMessageWithInt:withInt:);
  methods[10].selector = @selector(fastReadMailboxMessageWithInt:withInt:withByte:);
  methods[11].selector = @selector(fastReadMailboxMessageLength);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "writeMailboxMessage", "[B", "LComStSt25sdkSTException;", "I[B", "I[BB", "readMailboxMessage", "II", "IIB", "fastWriteMailboxMessage", "fastReadMailboxMessage" };
  static const J2ObjcClassInfo _ComStSt25sdkFastTransferModeInterface = { "FastTransferModeInterface", "com.st.st25sdk", ptrTable, methods, NULL, 7, 0x609, 12, 0, -1, -1, -1, -1, -1 };
  return &_ComStSt25sdkFastTransferModeInterface;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComStSt25sdkFastTransferModeInterface)
