//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/STLog.java
//

#include "J2ObjC_source.h"
#include "com/st/st25sdk/STLog.h"
#include "java/util/logging/Level.h"
#include "java/util/logging/Logger.h"

inline JavaUtilLoggingLogger *ComStSt25sdkSTLog_get_sLogger(void);
inline JavaUtilLoggingLogger *ComStSt25sdkSTLog_set_sLogger(JavaUtilLoggingLogger *value);
static JavaUtilLoggingLogger *ComStSt25sdkSTLog_sLogger;
J2OBJC_STATIC_FIELD_OBJ(ComStSt25sdkSTLog, sLogger, JavaUtilLoggingLogger *)

@implementation ComStSt25sdkSTLog

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComStSt25sdkSTLog_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)init__ {
  ComStSt25sdkSTLog_init__();
}

+ (void)setLevelWithJavaUtilLoggingLevel:(JavaUtilLoggingLevel *)newLevel {
  ComStSt25sdkSTLog_setLevelWithJavaUtilLoggingLevel_(newLevel);
}

+ (void)eWithNSString:(NSString *)msg {
  ComStSt25sdkSTLog_eWithNSString_(msg);
}

+ (void)wWithNSString:(NSString *)msg {
  ComStSt25sdkSTLog_wWithNSString_(msg);
}

+ (void)iWithNSString:(NSString *)msg {
  ComStSt25sdkSTLog_iWithNSString_(msg);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 0, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 5, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 6, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(init__);
  methods[2].selector = @selector(setLevelWithJavaUtilLoggingLevel:);
  methods[3].selector = @selector(eWithNSString:);
  methods[4].selector = @selector(wWithNSString:);
  methods[5].selector = @selector(iWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "sLogger", "LJavaUtilLoggingLogger;", .constantValue.asLong = 0, 0xa, -1, 7, -1, -1 },
  };
  static const void *ptrTable[] = { "init", "setLevel", "LJavaUtilLoggingLevel;", "e", "LNSString;", "w", "i", &ComStSt25sdkSTLog_sLogger };
  static const J2ObjcClassInfo _ComStSt25sdkSTLog = { "STLog", "com.st.st25sdk", ptrTable, methods, fields, 7, 0x1, 6, 1, -1, -1, -1, -1, -1 };
  return &_ComStSt25sdkSTLog;
}

@end

void ComStSt25sdkSTLog_init(ComStSt25sdkSTLog *self) {
  NSObject_init(self);
}

ComStSt25sdkSTLog *new_ComStSt25sdkSTLog_init() {
  J2OBJC_NEW_IMPL(ComStSt25sdkSTLog, init)
}

ComStSt25sdkSTLog *create_ComStSt25sdkSTLog_init() {
  J2OBJC_CREATE_IMPL(ComStSt25sdkSTLog, init)
}

void ComStSt25sdkSTLog_init__() {
  ComStSt25sdkSTLog_initialize();
  ComStSt25sdkSTLog_sLogger = JavaUtilLoggingLogger_getLoggerWithNSString_(@"ST25SDK");
  [((JavaUtilLoggingLogger *) nil_chk(ComStSt25sdkSTLog_sLogger)) setLevelWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, WARNING)];
}

void ComStSt25sdkSTLog_setLevelWithJavaUtilLoggingLevel_(JavaUtilLoggingLevel *newLevel) {
  ComStSt25sdkSTLog_initialize();
  if (ComStSt25sdkSTLog_sLogger != nil) {
    [ComStSt25sdkSTLog_sLogger setLevelWithJavaUtilLoggingLevel:newLevel];
  }
}

void ComStSt25sdkSTLog_eWithNSString_(NSString *msg) {
  ComStSt25sdkSTLog_initialize();
  if (ComStSt25sdkSTLog_sLogger == nil) {
    ComStSt25sdkSTLog_init__();
  }
  [((JavaUtilLoggingLogger *) nil_chk(ComStSt25sdkSTLog_sLogger)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, SEVERE) withNSString:msg];
}

void ComStSt25sdkSTLog_wWithNSString_(NSString *msg) {
  ComStSt25sdkSTLog_initialize();
  if (ComStSt25sdkSTLog_sLogger == nil) {
    ComStSt25sdkSTLog_init__();
  }
  [((JavaUtilLoggingLogger *) nil_chk(ComStSt25sdkSTLog_sLogger)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, WARNING) withNSString:msg];
}

void ComStSt25sdkSTLog_iWithNSString_(NSString *msg) {
  ComStSt25sdkSTLog_initialize();
  if (ComStSt25sdkSTLog_sLogger == nil) {
    ComStSt25sdkSTLog_init__();
  }
  [((JavaUtilLoggingLogger *) nil_chk(ComStSt25sdkSTLog_sLogger)) logWithJavaUtilLoggingLevel:JreLoadStatic(JavaUtilLoggingLevel, INFO) withNSString:msg];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComStSt25sdkSTLog)
