//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/TagHelper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkTagHelper")
#ifdef RESTRICT_ComStSt25sdkTagHelper
#define INCLUDE_ALL_ComStSt25sdkTagHelper 0
#else
#define INCLUDE_ALL_ComStSt25sdkTagHelper 1
#endif
#undef RESTRICT_ComStSt25sdkTagHelper

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkTagHelper_) && (INCLUDE_ALL_ComStSt25sdkTagHelper || defined(INCLUDE_ComStSt25sdkTagHelper))
#define ComStSt25sdkTagHelper_

@class ComStSt25sdkNFCTag;
@class ComStSt25sdkNFCTag_NfcTagTypes;
@class ComStSt25sdkTagHelper_ProductID;
@class IOSByteArray;
@class IOSObjectArray;
@protocol ComStSt25sdkRFReaderInterface;

@interface ComStSt25sdkTagHelper : NSObject
@property (readonly, class) jint PWD_ON_32_BITS NS_SWIFT_NAME(PWD_ON_32_BITS);
@property (readonly, class) jint PWD_ON_64_BITS NS_SWIFT_NAME(PWD_ON_64_BITS);
@property (readonly, class) jint PWD_ON_96_BITS NS_SWIFT_NAME(PWD_ON_96_BITS);
@property (readonly, class) jint PWD_ON_128_BITS NS_SWIFT_NAME(PWD_ON_128_BITS);
@property (readonly, class) jbyte DSFID_MASK NS_SWIFT_NAME(DSFID_MASK);
@property (readonly, class) jbyte AFI_MASK NS_SWIFT_NAME(AFI_MASK);
@property (readonly, class) jbyte VICC_MEM_SIZE_MASK NS_SWIFT_NAME(VICC_MEM_SIZE_MASK);
@property (readonly, class) jbyte ICREF_MASK NS_SWIFT_NAME(ICREF_MASK);
@property (readonly, class) jbyte PROTOCOL_CODE_ISO14443B NS_SWIFT_NAME(PROTOCOL_CODE_ISO14443B);
@property (readonly, class) jbyte PROTOCOL_CODE_ISO14443SR NS_SWIFT_NAME(PROTOCOL_CODE_ISO14443SR);
@property (readonly, class) jbyte PROTOCOL_CODE_ISO15693 NS_SWIFT_NAME(PROTOCOL_CODE_ISO15693);
@property (readonly, class) IOSObjectArray *ICManufacturers NS_SWIFT_NAME(ICManufacturers);

+ (jint)PWD_ON_32_BITS;

+ (jint)PWD_ON_64_BITS;

+ (jint)PWD_ON_96_BITS;

+ (jint)PWD_ON_128_BITS;

+ (jbyte)DSFID_MASK;

+ (jbyte)AFI_MASK;

+ (jbyte)VICC_MEM_SIZE_MASK;

+ (jbyte)ICREF_MASK;

+ (jbyte)PROTOCOL_CODE_ISO14443B;

+ (jbyte)PROTOCOL_CODE_ISO14443SR;

+ (jbyte)PROTOCOL_CODE_ISO15693;

+ (IOSObjectArray *)ICManufacturers;

#pragma mark Public

- (instancetype __nonnull)init;

+ (ComStSt25sdkTagHelper_ProductID *)getIso14443SRProductIdWithInt:(jint)manufacturerID
                                                           withInt:(jint)productCode;

+ (NSString *)getManufacturerNameWithComStSt25sdkNFCTag:(ComStSt25sdkNFCTag *)tag;

+ (jint)getProductCodeWithByteArray:(IOSByteArray *)uid
 withComStSt25sdkNFCTag_NfcTagTypes:(ComStSt25sdkNFCTag_NfcTagTypes *)tagType;

+ (ComStSt25sdkTagHelper_ProductID *)getType4ProductIdWithInt:(jint)manufacturerID
                                                      withInt:(jint)productCode;

+ (ComStSt25sdkTagHelper_ProductID *)identifyIso14443aType2Type4aProductWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                                                            withByteArray:(IOSByteArray *)uid;

+ (ComStSt25sdkTagHelper_ProductID *)identifyIso14443BProductWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                                                 withByteArray:(IOSByteArray *)uid;

+ (ComStSt25sdkTagHelper_ProductID *)identifyIso14443SRProductWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                                                  withByteArray:(IOSByteArray *)uid;

+ (ComStSt25sdkTagHelper_ProductID *)identifyPicopassProductWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                                                withByteArray:(IOSByteArray *)uid;

+ (ComStSt25sdkTagHelper_ProductID *)identifyProductWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                                        withByteArray:(IOSByteArray *)uid;

+ (ComStSt25sdkTagHelper_ProductID *)identifyType3ProductWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                                             withByteArray:(IOSByteArray *)uid;

+ (ComStSt25sdkTagHelper_ProductID *)identifyType4ProductWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                                             withByteArray:(IOSByteArray *)uid;

+ (ComStSt25sdkTagHelper_ProductID *)identifyTypeVProductWithComStSt25sdkRFReaderInterface:(id<ComStSt25sdkRFReaderInterface>)readerInterface
                                                                             withByteArray:(IOSByteArray *)uid;

@end

J2OBJC_STATIC_INIT(ComStSt25sdkTagHelper)

inline jint ComStSt25sdkTagHelper_get_PWD_ON_32_BITS(void);
#define ComStSt25sdkTagHelper_PWD_ON_32_BITS 32
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, PWD_ON_32_BITS, jint)

inline jint ComStSt25sdkTagHelper_get_PWD_ON_64_BITS(void);
#define ComStSt25sdkTagHelper_PWD_ON_64_BITS 64
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, PWD_ON_64_BITS, jint)

inline jint ComStSt25sdkTagHelper_get_PWD_ON_96_BITS(void);
#define ComStSt25sdkTagHelper_PWD_ON_96_BITS 96
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, PWD_ON_96_BITS, jint)

inline jint ComStSt25sdkTagHelper_get_PWD_ON_128_BITS(void);
#define ComStSt25sdkTagHelper_PWD_ON_128_BITS 128
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, PWD_ON_128_BITS, jint)

inline jbyte ComStSt25sdkTagHelper_get_DSFID_MASK(void);
#define ComStSt25sdkTagHelper_DSFID_MASK 1
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, DSFID_MASK, jbyte)

inline jbyte ComStSt25sdkTagHelper_get_AFI_MASK(void);
#define ComStSt25sdkTagHelper_AFI_MASK 2
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, AFI_MASK, jbyte)

inline jbyte ComStSt25sdkTagHelper_get_VICC_MEM_SIZE_MASK(void);
#define ComStSt25sdkTagHelper_VICC_MEM_SIZE_MASK 4
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, VICC_MEM_SIZE_MASK, jbyte)

inline jbyte ComStSt25sdkTagHelper_get_ICREF_MASK(void);
#define ComStSt25sdkTagHelper_ICREF_MASK 8
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, ICREF_MASK, jbyte)

inline jbyte ComStSt25sdkTagHelper_get_PROTOCOL_CODE_ISO14443B(void);
#define ComStSt25sdkTagHelper_PROTOCOL_CODE_ISO14443B -48
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, PROTOCOL_CODE_ISO14443B, jbyte)

inline jbyte ComStSt25sdkTagHelper_get_PROTOCOL_CODE_ISO14443SR(void);
#define ComStSt25sdkTagHelper_PROTOCOL_CODE_ISO14443SR -48
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, PROTOCOL_CODE_ISO14443SR, jbyte)

inline jbyte ComStSt25sdkTagHelper_get_PROTOCOL_CODE_ISO15693(void);
#define ComStSt25sdkTagHelper_PROTOCOL_CODE_ISO15693 -32
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkTagHelper, PROTOCOL_CODE_ISO15693, jbyte)

inline IOSObjectArray *ComStSt25sdkTagHelper_get_ICManufacturers(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSObjectArray *ComStSt25sdkTagHelper_ICManufacturers;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComStSt25sdkTagHelper, ICManufacturers, IOSObjectArray *)

FOUNDATION_EXPORT void ComStSt25sdkTagHelper_init(ComStSt25sdkTagHelper *self);

FOUNDATION_EXPORT ComStSt25sdkTagHelper *new_ComStSt25sdkTagHelper_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkTagHelper *create_ComStSt25sdkTagHelper_init(void);

FOUNDATION_EXPORT NSString *ComStSt25sdkTagHelper_getManufacturerNameWithComStSt25sdkNFCTag_(ComStSt25sdkNFCTag *tag);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_identifyProductWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_identifyTypeVProductWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_identifyType4ProductWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_identifyIso14443aType2Type4aProductWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_identifyType3ProductWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_identifyIso14443BProductWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_identifyIso14443SRProductWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_identifyPicopassProductWithComStSt25sdkRFReaderInterface_withByteArray_(id<ComStSt25sdkRFReaderInterface> readerInterface, IOSByteArray *uid);

FOUNDATION_EXPORT jint ComStSt25sdkTagHelper_getProductCodeWithByteArray_withComStSt25sdkNFCTag_NfcTagTypes_(IOSByteArray *uid, ComStSt25sdkNFCTag_NfcTagTypes *tagType);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_getType4ProductIdWithInt_withInt_(jint manufacturerID, jint productCode);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_getIso14443SRProductIdWithInt_withInt_(jint manufacturerID, jint productCode);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkTagHelper)

#endif

#if !defined (ComStSt25sdkTagHelper_ReadWriteProtection_) && (INCLUDE_ALL_ComStSt25sdkTagHelper || defined(INCLUDE_ComStSt25sdkTagHelper_ReadWriteProtection))
#define ComStSt25sdkTagHelper_ReadWriteProtection_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComStSt25sdkTagHelper_ReadWriteProtection_Enum) {
  ComStSt25sdkTagHelper_ReadWriteProtection_Enum_READABLE_AND_WRITABLE = 0,
  ComStSt25sdkTagHelper_ReadWriteProtection_Enum_READABLE_AND_WRITE_PROTECTED_BY_PWD = 1,
  ComStSt25sdkTagHelper_ReadWriteProtection_Enum_READ_AND_WRITE_PROTECTED_BY_PWD = 2,
  ComStSt25sdkTagHelper_ReadWriteProtection_Enum_READ_PROTECTED_BY_PWD_AND_WRITE_IMPOSSIBLE = 3,
  ComStSt25sdkTagHelper_ReadWriteProtection_Enum_READABLE_AND_WRITE_IMPOSSIBLE = 4,
  ComStSt25sdkTagHelper_ReadWriteProtection_Enum_WRITEABLE_AND_READ_PROTECTED_BY_PWD = 5,
};

@interface ComStSt25sdkTagHelper_ReadWriteProtection : JavaLangEnum

@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ReadWriteProtection *READABLE_AND_WRITABLE NS_SWIFT_NAME(READABLE_AND_WRITABLE);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ReadWriteProtection *READABLE_AND_WRITE_PROTECTED_BY_PWD NS_SWIFT_NAME(READABLE_AND_WRITE_PROTECTED_BY_PWD);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ReadWriteProtection *READ_AND_WRITE_PROTECTED_BY_PWD NS_SWIFT_NAME(READ_AND_WRITE_PROTECTED_BY_PWD);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ReadWriteProtection *READ_PROTECTED_BY_PWD_AND_WRITE_IMPOSSIBLE NS_SWIFT_NAME(READ_PROTECTED_BY_PWD_AND_WRITE_IMPOSSIBLE);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ReadWriteProtection *READABLE_AND_WRITE_IMPOSSIBLE NS_SWIFT_NAME(READABLE_AND_WRITE_IMPOSSIBLE);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ReadWriteProtection *WRITEABLE_AND_READ_PROTECTED_BY_PWD NS_SWIFT_NAME(WRITEABLE_AND_READ_PROTECTED_BY_PWD);
+ (ComStSt25sdkTagHelper_ReadWriteProtection * __nonnull)READABLE_AND_WRITABLE;

+ (ComStSt25sdkTagHelper_ReadWriteProtection * __nonnull)READABLE_AND_WRITE_PROTECTED_BY_PWD;

+ (ComStSt25sdkTagHelper_ReadWriteProtection * __nonnull)READ_AND_WRITE_PROTECTED_BY_PWD;

+ (ComStSt25sdkTagHelper_ReadWriteProtection * __nonnull)READ_PROTECTED_BY_PWD_AND_WRITE_IMPOSSIBLE;

+ (ComStSt25sdkTagHelper_ReadWriteProtection * __nonnull)READABLE_AND_WRITE_IMPOSSIBLE;

+ (ComStSt25sdkTagHelper_ReadWriteProtection * __nonnull)WRITEABLE_AND_READ_PROTECTED_BY_PWD;

#pragma mark Public

+ (ComStSt25sdkTagHelper_ReadWriteProtection *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComStSt25sdkTagHelper_ReadWriteProtection_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ComStSt25sdkTagHelper_ReadWriteProtection)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkTagHelper_ReadWriteProtection_values_[];

inline ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkTagHelper_ReadWriteProtection_get_READABLE_AND_WRITABLE(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ReadWriteProtection, READABLE_AND_WRITABLE)

inline ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkTagHelper_ReadWriteProtection_get_READABLE_AND_WRITE_PROTECTED_BY_PWD(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ReadWriteProtection, READABLE_AND_WRITE_PROTECTED_BY_PWD)

inline ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkTagHelper_ReadWriteProtection_get_READ_AND_WRITE_PROTECTED_BY_PWD(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ReadWriteProtection, READ_AND_WRITE_PROTECTED_BY_PWD)

inline ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkTagHelper_ReadWriteProtection_get_READ_PROTECTED_BY_PWD_AND_WRITE_IMPOSSIBLE(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ReadWriteProtection, READ_PROTECTED_BY_PWD_AND_WRITE_IMPOSSIBLE)

inline ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkTagHelper_ReadWriteProtection_get_READABLE_AND_WRITE_IMPOSSIBLE(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ReadWriteProtection, READABLE_AND_WRITE_IMPOSSIBLE)

inline ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkTagHelper_ReadWriteProtection_get_WRITEABLE_AND_READ_PROTECTED_BY_PWD(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ReadWriteProtection, WRITEABLE_AND_READ_PROTECTED_BY_PWD)

FOUNDATION_EXPORT IOSObjectArray *ComStSt25sdkTagHelper_ReadWriteProtection_values(void);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkTagHelper_ReadWriteProtection_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ReadWriteProtection *ComStSt25sdkTagHelper_ReadWriteProtection_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkTagHelper_ReadWriteProtection)

#endif

#if !defined (ComStSt25sdkTagHelper_ProductID_) && (INCLUDE_ALL_ComStSt25sdkTagHelper || defined(INCLUDE_ComStSt25sdkTagHelper_ProductID))
#define ComStSt25sdkTagHelper_ProductID_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComStSt25sdkTagHelper_ProductID_Enum) {
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_UNKNOWN = 0,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_TYPE4 = 1,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_ISO14443A = 2,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_TYPE1 = 3,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_TYPE3 = 4,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_ISO18092 = 5,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_TYPE2 = 6,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TN01K = 7,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TN512 = 8,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_TYPE4A = 9,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_M24SR02_Y = 10,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_M24SR04_Y = 11,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_M24SR04_G = 12,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_M24SR16_Y = 13,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_M24SR64_Y = 14,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA512 = 15,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA512_K = 16,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA512B = 17,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA02K = 18,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA02KB = 19,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA02K_P = 20,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA02KB_P = 21,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA02K_D = 22,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA02KB_D = 23,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA16K = 24,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TA64K = 25,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_SRTAG2K = 26,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_SRTAG2K_D = 27,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_ISO14443B = 28,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_TYPE4B = 29,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_ISO14443SR = 30,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TB512_AC = 31,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TB512_AT = 32,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TB02K = 33,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TB04K = 34,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_SRi512 = 35,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_SRi2K = 36,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_SRi4K = 37,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_SRT512 = 38,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_SRiX4K = 39,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_TYPE5_AND_ISO15693 = 40,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_TYPE5 = 41,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_LRiS64K = 42,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_M24LR64_R = 43,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_M24LR04E_R = 44,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_M24LR16E_R = 45,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_M24LR64E_R = 46,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV04K_I = 47,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV04K_J = 48,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV16K_I = 49,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV16K_J = 50,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV64K_I = 51,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV64K_J = 52,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TV512 = 53,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TV512C = 54,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV02K_W1 = 55,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV02K_W2 = 56,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV04KC_I = 57,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV04KC_J = 58,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV16KC_I = 59,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV16KC_J = 60,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV64KC_I = 61,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25DV64KC_J = 62,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TV02K = 63,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TV02KC = 64,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TV04K_P = 65,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TV16K = 66,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST25TV64K = 67,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_LRi64 = 68,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_LRi512 = 69,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_LRi1K = 70,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_LRi2K = 71,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_LRiS2K = 72,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_GENERIC_PICOPASS = 73,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_RX95HF = 74,
  ComStSt25sdkTagHelper_ProductID_Enum_PRODUCT_ST_ST95HF = 75,
};

@interface ComStSt25sdkTagHelper_ProductID : JavaLangEnum

@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_UNKNOWN NS_SWIFT_NAME(PRODUCT_UNKNOWN);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_TYPE4 NS_SWIFT_NAME(PRODUCT_GENERIC_TYPE4);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_ISO14443A NS_SWIFT_NAME(PRODUCT_GENERIC_ISO14443A);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_TYPE1 NS_SWIFT_NAME(PRODUCT_GENERIC_TYPE1);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_TYPE3 NS_SWIFT_NAME(PRODUCT_GENERIC_TYPE3);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_ISO18092 NS_SWIFT_NAME(PRODUCT_GENERIC_ISO18092);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_TYPE2 NS_SWIFT_NAME(PRODUCT_GENERIC_TYPE2);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TN01K NS_SWIFT_NAME(PRODUCT_ST_ST25TN01K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TN512 NS_SWIFT_NAME(PRODUCT_ST_ST25TN512);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_TYPE4A NS_SWIFT_NAME(PRODUCT_GENERIC_TYPE4A);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_M24SR02_Y NS_SWIFT_NAME(PRODUCT_ST_M24SR02_Y);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_M24SR04_Y NS_SWIFT_NAME(PRODUCT_ST_M24SR04_Y);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_M24SR04_G NS_SWIFT_NAME(PRODUCT_ST_M24SR04_G);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_M24SR16_Y NS_SWIFT_NAME(PRODUCT_ST_M24SR16_Y);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_M24SR64_Y NS_SWIFT_NAME(PRODUCT_ST_M24SR64_Y);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA512 NS_SWIFT_NAME(PRODUCT_ST_ST25TA512);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA512_K NS_SWIFT_NAME(PRODUCT_ST_ST25TA512_K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA512B NS_SWIFT_NAME(PRODUCT_ST_ST25TA512B);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA02K NS_SWIFT_NAME(PRODUCT_ST_ST25TA02K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA02KB NS_SWIFT_NAME(PRODUCT_ST_ST25TA02KB);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA02K_P NS_SWIFT_NAME(PRODUCT_ST_ST25TA02K_P);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA02KB_P NS_SWIFT_NAME(PRODUCT_ST_ST25TA02KB_P);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA02K_D NS_SWIFT_NAME(PRODUCT_ST_ST25TA02K_D);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA02KB_D NS_SWIFT_NAME(PRODUCT_ST_ST25TA02KB_D);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA16K NS_SWIFT_NAME(PRODUCT_ST_ST25TA16K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TA64K NS_SWIFT_NAME(PRODUCT_ST_ST25TA64K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_SRTAG2K NS_SWIFT_NAME(PRODUCT_ST_SRTAG2K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_SRTAG2K_D NS_SWIFT_NAME(PRODUCT_ST_SRTAG2K_D);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_ISO14443B NS_SWIFT_NAME(PRODUCT_GENERIC_ISO14443B);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_TYPE4B NS_SWIFT_NAME(PRODUCT_GENERIC_TYPE4B);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_ISO14443SR NS_SWIFT_NAME(PRODUCT_GENERIC_ISO14443SR);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TB512_AC NS_SWIFT_NAME(PRODUCT_ST_ST25TB512_AC);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TB512_AT NS_SWIFT_NAME(PRODUCT_ST_ST25TB512_AT);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TB02K NS_SWIFT_NAME(PRODUCT_ST_ST25TB02K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TB04K NS_SWIFT_NAME(PRODUCT_ST_ST25TB04K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_SRi512 NS_SWIFT_NAME(PRODUCT_ST_SRi512);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_SRi2K NS_SWIFT_NAME(PRODUCT_ST_SRi2K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_SRi4K NS_SWIFT_NAME(PRODUCT_ST_SRi4K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_SRT512 NS_SWIFT_NAME(PRODUCT_ST_SRT512);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_SRiX4K NS_SWIFT_NAME(PRODUCT_ST_SRiX4K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_TYPE5_AND_ISO15693 NS_SWIFT_NAME(PRODUCT_GENERIC_TYPE5_AND_ISO15693);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_TYPE5 NS_SWIFT_NAME(PRODUCT_GENERIC_TYPE5);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_LRiS64K NS_SWIFT_NAME(PRODUCT_ST_LRiS64K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_M24LR64_R NS_SWIFT_NAME(PRODUCT_ST_M24LR64_R);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_M24LR04E_R NS_SWIFT_NAME(PRODUCT_ST_M24LR04E_R);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_M24LR16E_R NS_SWIFT_NAME(PRODUCT_ST_M24LR16E_R);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_M24LR64E_R NS_SWIFT_NAME(PRODUCT_ST_M24LR64E_R);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV04K_I NS_SWIFT_NAME(PRODUCT_ST_ST25DV04K_I);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV04K_J NS_SWIFT_NAME(PRODUCT_ST_ST25DV04K_J);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV16K_I NS_SWIFT_NAME(PRODUCT_ST_ST25DV16K_I);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV16K_J NS_SWIFT_NAME(PRODUCT_ST_ST25DV16K_J);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV64K_I NS_SWIFT_NAME(PRODUCT_ST_ST25DV64K_I);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV64K_J NS_SWIFT_NAME(PRODUCT_ST_ST25DV64K_J);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TV512 NS_SWIFT_NAME(PRODUCT_ST_ST25TV512);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TV512C NS_SWIFT_NAME(PRODUCT_ST_ST25TV512C);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV02K_W1 NS_SWIFT_NAME(PRODUCT_ST_ST25DV02K_W1);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV02K_W2 NS_SWIFT_NAME(PRODUCT_ST_ST25DV02K_W2);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV04KC_I NS_SWIFT_NAME(PRODUCT_ST_ST25DV04KC_I);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV04KC_J NS_SWIFT_NAME(PRODUCT_ST_ST25DV04KC_J);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV16KC_I NS_SWIFT_NAME(PRODUCT_ST_ST25DV16KC_I);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV16KC_J NS_SWIFT_NAME(PRODUCT_ST_ST25DV16KC_J);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV64KC_I NS_SWIFT_NAME(PRODUCT_ST_ST25DV64KC_I);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25DV64KC_J NS_SWIFT_NAME(PRODUCT_ST_ST25DV64KC_J);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TV02K NS_SWIFT_NAME(PRODUCT_ST_ST25TV02K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TV02KC NS_SWIFT_NAME(PRODUCT_ST_ST25TV02KC);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TV04K_P NS_SWIFT_NAME(PRODUCT_ST_ST25TV04K_P);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TV16K NS_SWIFT_NAME(PRODUCT_ST_ST25TV16K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST25TV64K NS_SWIFT_NAME(PRODUCT_ST_ST25TV64K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_LRi64 NS_SWIFT_NAME(PRODUCT_ST_LRi64);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_LRi512 NS_SWIFT_NAME(PRODUCT_ST_LRi512);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_LRi1K NS_SWIFT_NAME(PRODUCT_ST_LRi1K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_LRi2K NS_SWIFT_NAME(PRODUCT_ST_LRi2K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_LRiS2K NS_SWIFT_NAME(PRODUCT_ST_LRiS2K);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_GENERIC_PICOPASS NS_SWIFT_NAME(PRODUCT_GENERIC_PICOPASS);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_RX95HF NS_SWIFT_NAME(PRODUCT_ST_RX95HF);
@property (readonly, class, nonnull) ComStSt25sdkTagHelper_ProductID *PRODUCT_ST_ST95HF NS_SWIFT_NAME(PRODUCT_ST_ST95HF);
+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_UNKNOWN;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_TYPE4;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_ISO14443A;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_TYPE1;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_TYPE3;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_ISO18092;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_TYPE2;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TN01K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TN512;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_TYPE4A;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_M24SR02_Y;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_M24SR04_Y;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_M24SR04_G;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_M24SR16_Y;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_M24SR64_Y;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA512;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA512_K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA512B;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA02K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA02KB;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA02K_P;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA02KB_P;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA02K_D;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA02KB_D;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA16K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TA64K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_SRTAG2K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_SRTAG2K_D;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_ISO14443B;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_TYPE4B;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_ISO14443SR;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TB512_AC;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TB512_AT;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TB02K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TB04K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_SRi512;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_SRi2K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_SRi4K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_SRT512;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_SRiX4K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_TYPE5_AND_ISO15693;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_TYPE5;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_LRiS64K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_M24LR64_R;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_M24LR04E_R;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_M24LR16E_R;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_M24LR64E_R;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV04K_I;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV04K_J;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV16K_I;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV16K_J;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV64K_I;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV64K_J;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TV512;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TV512C;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV02K_W1;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV02K_W2;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV04KC_I;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV04KC_J;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV16KC_I;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV16KC_J;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV64KC_I;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25DV64KC_J;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TV02K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TV02KC;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TV04K_P;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TV16K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST25TV64K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_LRi64;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_LRi512;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_LRi1K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_LRi2K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_LRiS2K;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_GENERIC_PICOPASS;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_RX95HF;

+ (ComStSt25sdkTagHelper_ProductID * __nonnull)PRODUCT_ST_ST95HF;

#pragma mark Public

- (NSString *)description;

+ (ComStSt25sdkTagHelper_ProductID *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComStSt25sdkTagHelper_ProductID_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ComStSt25sdkTagHelper_ProductID)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_values_[];

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_UNKNOWN(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_UNKNOWN)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_TYPE4(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_TYPE4)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_ISO14443A(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_ISO14443A)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_TYPE1(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_TYPE1)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_TYPE3(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_TYPE3)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_ISO18092(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_ISO18092)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_TYPE2(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_TYPE2)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TN01K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TN01K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TN512(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TN512)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_TYPE4A(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_TYPE4A)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_M24SR02_Y(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_M24SR02_Y)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_M24SR04_Y(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_M24SR04_Y)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_M24SR04_G(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_M24SR04_G)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_M24SR16_Y(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_M24SR16_Y)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_M24SR64_Y(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_M24SR64_Y)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA512(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA512)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA512_K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA512_K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA512B(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA512B)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA02K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA02K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA02KB(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA02KB)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA02K_P(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA02K_P)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA02KB_P(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA02KB_P)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA02K_D(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA02K_D)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA02KB_D(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA02KB_D)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA16K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA16K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TA64K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TA64K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_SRTAG2K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_SRTAG2K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_SRTAG2K_D(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_SRTAG2K_D)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_ISO14443B(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_ISO14443B)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_TYPE4B(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_TYPE4B)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_ISO14443SR(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_ISO14443SR)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TB512_AC(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TB512_AC)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TB512_AT(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TB512_AT)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TB02K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TB02K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TB04K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TB04K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_SRi512(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_SRi512)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_SRi2K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_SRi2K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_SRi4K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_SRi4K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_SRT512(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_SRT512)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_SRiX4K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_SRiX4K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_TYPE5_AND_ISO15693(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_TYPE5_AND_ISO15693)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_TYPE5(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_TYPE5)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_LRiS64K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_LRiS64K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_M24LR64_R(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_M24LR64_R)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_M24LR04E_R(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_M24LR04E_R)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_M24LR16E_R(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_M24LR16E_R)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_M24LR64E_R(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_M24LR64E_R)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV04K_I(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV04K_I)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV04K_J(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV04K_J)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV16K_I(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV16K_I)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV16K_J(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV16K_J)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV64K_I(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV64K_I)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV64K_J(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV64K_J)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TV512(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TV512)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TV512C(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TV512C)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV02K_W1(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV02K_W1)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV02K_W2(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV02K_W2)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV04KC_I(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV04KC_I)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV04KC_J(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV04KC_J)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV16KC_I(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV16KC_I)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV16KC_J(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV16KC_J)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV64KC_I(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV64KC_I)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25DV64KC_J(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25DV64KC_J)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TV02K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TV02K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TV02KC(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TV02KC)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TV04K_P(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TV04K_P)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TV16K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TV16K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST25TV64K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST25TV64K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_LRi64(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_LRi64)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_LRi512(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_LRi512)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_LRi1K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_LRi1K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_LRi2K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_LRi2K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_LRiS2K(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_LRiS2K)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_GENERIC_PICOPASS(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_GENERIC_PICOPASS)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_RX95HF(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_RX95HF)

inline ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_get_PRODUCT_ST_ST95HF(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkTagHelper_ProductID, PRODUCT_ST_ST95HF)

FOUNDATION_EXPORT IOSObjectArray *ComStSt25sdkTagHelper_ProductID_values(void);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComStSt25sdkTagHelper_ProductID *ComStSt25sdkTagHelper_ProductID_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkTagHelper_ProductID)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkTagHelper")
