//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type5/st25dv/ST25DVDynRegisterMb.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVDynRegisterMb")
#ifdef RESTRICT_ComStSt25sdkType5St25dvST25DVDynRegisterMb
#define INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVDynRegisterMb 0
#else
#define INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVDynRegisterMb 1
#endif
#undef RESTRICT_ComStSt25sdkType5St25dvST25DVDynRegisterMb

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType5St25dvST25DVDynRegisterMb_) && (INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVDynRegisterMb || defined(INCLUDE_ComStSt25sdkType5St25dvST25DVDynRegisterMb))
#define ComStSt25sdkType5St25dvST25DVDynRegisterMb_

#define RESTRICT_ComStSt25sdkSTDynamicRegister 1
#define INCLUDE_ComStSt25sdkSTDynamicRegister 1
#include "com/st/st25sdk/STDynamicRegister.h"

@class ComStSt25sdkCommandIso15693CustomCommand;
@class ComStSt25sdkSTRegister_RegisterAccessRights;
@class ComStSt25sdkSTRegister_RegisterDataSize;
@class ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl;

@interface ComStSt25sdkType5St25dvST25DVDynRegisterMb : ComStSt25sdkSTDynamicRegister
@property (readonly, class) jbyte MB_EN_BIT_MASK NS_SWIFT_NAME(MB_EN_BIT_MASK);
@property (readonly, class) jbyte HOST_PUT_MSG_BIT_MASK NS_SWIFT_NAME(HOST_PUT_MSG_BIT_MASK);
@property (readonly, class) jbyte RF_PUT_MSG_BIT_MASK NS_SWIFT_NAME(RF_PUT_MSG_BIT_MASK);
@property (readonly, class) jbyte HOST_MISS_MSG_BIT_MASK NS_SWIFT_NAME(HOST_MISS_MSG_BIT_MASK);
@property (readonly, class) jbyte RF_MISS_MSG_BIT_MASK NS_SWIFT_NAME(RF_MISS_MSG_BIT_MASK);
@property (readonly, class) jbyte HOST_CURRENT_MSG_BIT_MASK NS_SWIFT_NAME(HOST_CURRENT_MSG_BIT_MASK);
@property (readonly, class) jbyte RF_CURRENT_MSG_BIT_MASK NS_SWIFT_NAME(RF_CURRENT_MSG_BIT_MASK);

+ (jbyte)MB_EN_BIT_MASK;

+ (jbyte)HOST_PUT_MSG_BIT_MASK;

+ (jbyte)RF_PUT_MSG_BIT_MASK;

+ (jbyte)HOST_MISS_MSG_BIT_MASK;

+ (jbyte)RF_MISS_MSG_BIT_MASK;

+ (jbyte)HOST_CURRENT_MSG_BIT_MASK;

+ (jbyte)RF_CURRENT_MSG_BIT_MASK;

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkCommandIso15693CustomCommand:(ComStSt25sdkCommandIso15693CustomCommand *)iso15693CustomCommand
                                                                   withInt:(jint)registerAddress
                                                              withNSString:(NSString *)registerName
                                                              withNSString:(NSString *)registerContentDescription
                           withComStSt25sdkSTRegister_RegisterAccessRights:(ComStSt25sdkSTRegister_RegisterAccessRights *)registerAccessRights
                               withComStSt25sdkSTRegister_RegisterDataSize:(ComStSt25sdkSTRegister_RegisterDataSize *)registerDataSize;

- (jboolean)isMBFieldEnabledWithComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl:(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *)mbControl;

- (jboolean)isMBFieldEnabledWithComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl:(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *)mbControl
                                                                               withBoolean:(jboolean)useFastCommand;

+ (ComStSt25sdkType5St25dvST25DVDynRegisterMb *)newInstanceWithComStSt25sdkCommandIso15693CustomCommand:(ComStSt25sdkCommandIso15693CustomCommand *)iso15693CustomCommand OBJC_METHOD_FAMILY_NONE;

- (void)setMBWithComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl:(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *)mbControl
                                                                withBoolean:(jboolean)enable;

- (void)setMBWithComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl:(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *)mbControl
                                                                withBoolean:(jboolean)enable
                                                                withBoolean:(jboolean)useFastCommand;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType5St25dvST25DVDynRegisterMb)

inline jbyte ComStSt25sdkType5St25dvST25DVDynRegisterMb_get_MB_EN_BIT_MASK(void);
#define ComStSt25sdkType5St25dvST25DVDynRegisterMb_MB_EN_BIT_MASK 1
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb, MB_EN_BIT_MASK, jbyte)

inline jbyte ComStSt25sdkType5St25dvST25DVDynRegisterMb_get_HOST_PUT_MSG_BIT_MASK(void);
#define ComStSt25sdkType5St25dvST25DVDynRegisterMb_HOST_PUT_MSG_BIT_MASK 2
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb, HOST_PUT_MSG_BIT_MASK, jbyte)

inline jbyte ComStSt25sdkType5St25dvST25DVDynRegisterMb_get_RF_PUT_MSG_BIT_MASK(void);
#define ComStSt25sdkType5St25dvST25DVDynRegisterMb_RF_PUT_MSG_BIT_MASK 4
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb, RF_PUT_MSG_BIT_MASK, jbyte)

inline jbyte ComStSt25sdkType5St25dvST25DVDynRegisterMb_get_HOST_MISS_MSG_BIT_MASK(void);
#define ComStSt25sdkType5St25dvST25DVDynRegisterMb_HOST_MISS_MSG_BIT_MASK 16
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb, HOST_MISS_MSG_BIT_MASK, jbyte)

inline jbyte ComStSt25sdkType5St25dvST25DVDynRegisterMb_get_RF_MISS_MSG_BIT_MASK(void);
#define ComStSt25sdkType5St25dvST25DVDynRegisterMb_RF_MISS_MSG_BIT_MASK 32
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb, RF_MISS_MSG_BIT_MASK, jbyte)

inline jbyte ComStSt25sdkType5St25dvST25DVDynRegisterMb_get_HOST_CURRENT_MSG_BIT_MASK(void);
#define ComStSt25sdkType5St25dvST25DVDynRegisterMb_HOST_CURRENT_MSG_BIT_MASK 64
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb, HOST_CURRENT_MSG_BIT_MASK, jbyte)

inline jbyte ComStSt25sdkType5St25dvST25DVDynRegisterMb_get_RF_CURRENT_MSG_BIT_MASK(void);
#define ComStSt25sdkType5St25dvST25DVDynRegisterMb_RF_CURRENT_MSG_BIT_MASK -128
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb, RF_CURRENT_MSG_BIT_MASK, jbyte)

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVDynRegisterMb *ComStSt25sdkType5St25dvST25DVDynRegisterMb_newInstanceWithComStSt25sdkCommandIso15693CustomCommand_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand);

FOUNDATION_EXPORT void ComStSt25sdkType5St25dvST25DVDynRegisterMb_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkType5St25dvST25DVDynRegisterMb *self, ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize);

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVDynRegisterMb *new_ComStSt25sdkType5St25dvST25DVDynRegisterMb_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVDynRegisterMb *create_ComStSt25sdkType5St25dvST25DVDynRegisterMb_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType5St25dvST25DVDynRegisterMb)

#endif

#if !defined (ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_) && (INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVDynRegisterMb || defined(INCLUDE_ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl))
#define ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_Enum) {
  ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_Enum_MB_EN = 0,
  ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_Enum_HOST_PUT_MSG = 1,
  ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_Enum_RF_PUT_MSG = 2,
  ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_Enum_HOST_MISS_MSG = 3,
  ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_Enum_RF_MISS_MSG = 4,
};

@interface ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl : JavaLangEnum

@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *MB_EN NS_SWIFT_NAME(MB_EN);
@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *HOST_PUT_MSG NS_SWIFT_NAME(HOST_PUT_MSG);
@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *RF_PUT_MSG NS_SWIFT_NAME(RF_PUT_MSG);
@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *HOST_MISS_MSG NS_SWIFT_NAME(HOST_MISS_MSG);
@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *RF_MISS_MSG NS_SWIFT_NAME(RF_MISS_MSG);
+ (ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl * __nonnull)MB_EN;

+ (ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl * __nonnull)HOST_PUT_MSG;

+ (ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl * __nonnull)RF_PUT_MSG;

+ (ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl * __nonnull)HOST_MISS_MSG;

+ (ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl * __nonnull)RF_MISS_MSG;

#pragma mark Public

+ (ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_values_[];

inline ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_get_MB_EN(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl, MB_EN)

inline ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_get_HOST_PUT_MSG(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl, HOST_PUT_MSG)

inline ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_get_RF_PUT_MSG(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl, RF_PUT_MSG)

inline ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_get_HOST_MISS_MSG(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl, HOST_MISS_MSG)

inline ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_get_RF_MISS_MSG(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl, RF_MISS_MSG)

FOUNDATION_EXPORT IOSObjectArray *ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_values(void);

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl *ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType5St25dvST25DVDynRegisterMb_ST25DVMBControl)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVDynRegisterMb")
