//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type5/st25dv/ST25DVRegisterLockCfg.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterLockCfg")
#ifdef RESTRICT_ComStSt25sdkType5St25dvST25DVRegisterLockCfg
#define INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterLockCfg 0
#else
#define INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterLockCfg 1
#endif
#undef RESTRICT_ComStSt25sdkType5St25dvST25DVRegisterLockCfg

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType5St25dvST25DVRegisterLockCfg_) && (INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterLockCfg || defined(INCLUDE_ComStSt25sdkType5St25dvST25DVRegisterLockCfg))
#define ComStSt25sdkType5St25dvST25DVRegisterLockCfg_

#define RESTRICT_ComStSt25sdkType5STType5Register 1
#define INCLUDE_ComStSt25sdkType5STType5Register 1
#include "com/st/st25sdk/type5/STType5Register.h"

@class ComStSt25sdkCommandIso15693CustomCommand;
@class ComStSt25sdkSTRegister_RegisterAccessRights;
@class ComStSt25sdkSTRegister_RegisterDataSize;

@interface ComStSt25sdkType5St25dvST25DVRegisterLockCfg : ComStSt25sdkType5STType5Register
@property (readonly, class) jbyte LOCK_CFG_BIT_MASK NS_SWIFT_NAME(LOCK_CFG_BIT_MASK);
@property (readonly, class) jbyte RFU_BIT_MASK NS_SWIFT_NAME(RFU_BIT_MASK);

+ (jbyte)LOCK_CFG_BIT_MASK;

+ (jbyte)RFU_BIT_MASK;

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkCommandIso15693CustomCommand:(ComStSt25sdkCommandIso15693CustomCommand *)iso15693CustomCommand
                                                                   withInt:(jint)registerAddress
                                                              withNSString:(NSString *)registerName
                                                              withNSString:(NSString *)registerContentDescription
                           withComStSt25sdkSTRegister_RegisterAccessRights:(ComStSt25sdkSTRegister_RegisterAccessRights *)registerAccessRights
                               withComStSt25sdkSTRegister_RegisterDataSize:(ComStSt25sdkSTRegister_RegisterDataSize *)registerDataSize;

- (jboolean)isLockCfgEnabled;

+ (ComStSt25sdkType5St25dvST25DVRegisterLockCfg *)newInstanceWithComStSt25sdkCommandIso15693CustomCommand:(ComStSt25sdkCommandIso15693CustomCommand *)iso15693CustomCommand OBJC_METHOD_FAMILY_NONE;

- (void)setLockCfgModeWithBoolean:(jboolean)enable;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithComStSt25sdkCommandIso15693CustomCommand:(ComStSt25sdkCommandIso15693CustomCommand *)arg0
                                                                   withInt:(jint)arg1
                                                                   withInt:(jint)arg2
                                                              withNSString:(NSString *)arg3
                                                              withNSString:(NSString *)arg4
                           withComStSt25sdkSTRegister_RegisterAccessRights:(ComStSt25sdkSTRegister_RegisterAccessRights *)arg5
                               withComStSt25sdkSTRegister_RegisterDataSize:(ComStSt25sdkSTRegister_RegisterDataSize *)arg6 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType5St25dvST25DVRegisterLockCfg)

inline jbyte ComStSt25sdkType5St25dvST25DVRegisterLockCfg_get_LOCK_CFG_BIT_MASK(void);
#define ComStSt25sdkType5St25dvST25DVRegisterLockCfg_LOCK_CFG_BIT_MASK 1
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25dvST25DVRegisterLockCfg, LOCK_CFG_BIT_MASK, jbyte)

inline jbyte ComStSt25sdkType5St25dvST25DVRegisterLockCfg_get_RFU_BIT_MASK(void);
#define ComStSt25sdkType5St25dvST25DVRegisterLockCfg_RFU_BIT_MASK -2
J2OBJC_STATIC_FIELD_CONSTANT(ComStSt25sdkType5St25dvST25DVRegisterLockCfg, RFU_BIT_MASK, jbyte)

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterLockCfg *ComStSt25sdkType5St25dvST25DVRegisterLockCfg_newInstanceWithComStSt25sdkCommandIso15693CustomCommand_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand);

FOUNDATION_EXPORT void ComStSt25sdkType5St25dvST25DVRegisterLockCfg_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkType5St25dvST25DVRegisterLockCfg *self, ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize);

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterLockCfg *new_ComStSt25sdkType5St25dvST25DVRegisterLockCfg_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterLockCfg *create_ComStSt25sdkType5St25dvST25DVRegisterLockCfg_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType5St25dvST25DVRegisterLockCfg)

#endif

#if !defined (ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_) && (INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterLockCfg || defined(INCLUDE_ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl))
#define ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_Enum) {
  ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_Enum_LOCK_CFG = 0,
  ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_Enum_RFU = 1,
};

@interface ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl : JavaLangEnum

@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl *LOCK_CFG NS_SWIFT_NAME(LOCK_CFG);
@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl *RFU NS_SWIFT_NAME(RFU);
+ (ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl * __nonnull)LOCK_CFG;

+ (ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl * __nonnull)RFU;

#pragma mark Public

+ (ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl *ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_values_[];

inline ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl *ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_get_LOCK_CFG(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl, LOCK_CFG)

inline ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl *ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_get_RFU(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl, RFU)

FOUNDATION_EXPORT IOSObjectArray *ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_values(void);

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl *ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl *ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType5St25dvST25DVRegisterLockCfg_ST25DVRegisterLockCfgCtrl)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterLockCfg")
