//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: st25sdk_ios/type5/st25dv/ST25DVRegisterRfAiSS.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS")
#ifdef RESTRICT_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS
#define INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS 0
#else
#define INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS 1
#endif
#undef RESTRICT_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_) && (INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS || defined(INCLUDE_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS))
#define ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_

#define RESTRICT_ComStSt25sdkType5STType5Register 1
#define INCLUDE_ComStSt25sdkType5STType5Register 1
#include "com/st/st25sdk/type5/STType5Register.h"

@class ComStSt25sdkCommandIso15693CustomCommand;
@class ComStSt25sdkSTRegister_RegisterAccessRights;
@class ComStSt25sdkSTRegister_RegisterDataSize;
@class ComStSt25sdkTagHelper_ReadWriteProtection;
@class ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl;

@interface ComStSt25sdkType5St25dvST25DVRegisterRfAiSS : ComStSt25sdkType5STType5Register

#pragma mark Public

- (instancetype __nonnull)initWithComStSt25sdkCommandIso15693CustomCommand:(ComStSt25sdkCommandIso15693CustomCommand *)iso15693CustomCommand
                                                                   withInt:(jint)areaId
                                                                   withInt:(jint)registerAddress
                                                              withNSString:(NSString *)registerName
                                                              withNSString:(NSString *)registerContentDescription
                           withComStSt25sdkSTRegister_RegisterAccessRights:(ComStSt25sdkSTRegister_RegisterAccessRights *)registerAccessRights
                               withComStSt25sdkSTRegister_RegisterDataSize:(ComStSt25sdkSTRegister_RegisterDataSize *)registerDataSize;

- (ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *)getSSPWDControl;

- (ComStSt25sdkTagHelper_ReadWriteProtection *)getSSRWProtection;

+ (ComStSt25sdkType5St25dvST25DVRegisterRfAiSS *)newInstanceWithComStSt25sdkCommandIso15693CustomCommand:(ComStSt25sdkCommandIso15693CustomCommand *)iso15693CustomCommand
                                                                                                 withInt:(jint)index OBJC_METHOD_FAMILY_NONE;

- (void)setSSPWDControlWithComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl:(ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *)pwdControl;

- (void)setSSReadWriteProtectionWithComStSt25sdkTagHelper_ReadWriteProtection:(ComStSt25sdkTagHelper_ReadWriteProtection *)rwProtection;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithComStSt25sdkCommandIso15693CustomCommand:(ComStSt25sdkCommandIso15693CustomCommand *)arg0
                                                                   withInt:(jint)arg1
                                                              withNSString:(NSString *)arg2
                                                              withNSString:(NSString *)arg3
                           withComStSt25sdkSTRegister_RegisterAccessRights:(ComStSt25sdkSTRegister_RegisterAccessRights *)arg4
                               withComStSt25sdkSTRegister_RegisterDataSize:(ComStSt25sdkSTRegister_RegisterDataSize *)arg5 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComStSt25sdkType5St25dvST25DVRegisterRfAiSS)

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterRfAiSS *ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_newInstanceWithComStSt25sdkCommandIso15693CustomCommand_withInt_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint index);

FOUNDATION_EXPORT void ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkType5St25dvST25DVRegisterRfAiSS *self, ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint areaId, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize);

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterRfAiSS *new_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint areaId, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterRfAiSS *create_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_initWithComStSt25sdkCommandIso15693CustomCommand_withInt_withInt_withNSString_withNSString_withComStSt25sdkSTRegister_RegisterAccessRights_withComStSt25sdkSTRegister_RegisterDataSize_(ComStSt25sdkCommandIso15693CustomCommand *iso15693CustomCommand, jint areaId, jint registerAddress, NSString *registerName, NSString *registerContentDescription, ComStSt25sdkSTRegister_RegisterAccessRights *registerAccessRights, ComStSt25sdkSTRegister_RegisterDataSize *registerDataSize);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType5St25dvST25DVRegisterRfAiSS)

#endif

#if !defined (ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_) && (INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS || defined(INCLUDE_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl))
#define ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_Enum) {
  ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_Enum_NO_PWD_SELECTED = 0,
  ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_Enum_PROTECTED_BY_PWD1 = 1,
  ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_Enum_PROTECTED_BY_PWD2 = 2,
  ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_Enum_PROTECTED_BY_PWD3 = 3,
};

@interface ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl : JavaLangEnum

@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *NO_PWD_SELECTED NS_SWIFT_NAME(NO_PWD_SELECTED);
@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *PROTECTED_BY_PWD1 NS_SWIFT_NAME(PROTECTED_BY_PWD1);
@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *PROTECTED_BY_PWD2 NS_SWIFT_NAME(PROTECTED_BY_PWD2);
@property (readonly, class, nonnull) ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *PROTECTED_BY_PWD3 NS_SWIFT_NAME(PROTECTED_BY_PWD3);
+ (ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl * __nonnull)NO_PWD_SELECTED;

+ (ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl * __nonnull)PROTECTED_BY_PWD1;

+ (ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl * __nonnull)PROTECTED_BY_PWD2;

+ (ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl * __nonnull)PROTECTED_BY_PWD3;

#pragma mark Public

+ (ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_values_[];

inline ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_get_NO_PWD_SELECTED(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl, NO_PWD_SELECTED)

inline ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_get_PROTECTED_BY_PWD1(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl, PROTECTED_BY_PWD1)

inline ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_get_PROTECTED_BY_PWD2(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl, PROTECTED_BY_PWD2)

inline ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_get_PROTECTED_BY_PWD3(void);
J2OBJC_ENUM_CONSTANT(ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl, PROTECTED_BY_PWD3)

FOUNDATION_EXPORT IOSObjectArray *ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_values(void);

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl *ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComStSt25sdkType5St25dvST25DVRegisterRfAiSS_ST25DVSecurityStatusPWDControl)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComStSt25sdkType5St25dvST25DVRegisterRfAiSS")
